// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Server.proto
#ifndef GRPC_Server_2eproto__INCLUDED
#define GRPC_Server_2eproto__INCLUDED

#include "Server.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace kapa {
namespace tarracsh {
namespace app {
namespace server {
namespace digest {

class PublicDigest final {
 public:
  static constexpr char const* service_full_name() {
    return "kapa.tarracsh.app.server.digest.PublicDigest";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Quit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::kapa::tarracsh::app::server::digest::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::Empty>> AsyncQuit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::Empty>>(AsyncQuitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::Empty>> PrepareAsyncQuit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::Empty>>(PrepareAsyncQuitRaw(context, request, cq));
    }
    virtual ::grpc::Status Diff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::kapa::tarracsh::app::server::digest::DiffResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::DiffResponse>> AsyncDiff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::DiffResponse>>(AsyncDiffRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::DiffResponse>> PrepareAsyncDiff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::DiffResponse>>(PrepareAsyncDiffRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Quit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty* request, ::kapa::tarracsh::app::server::digest::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Quit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty* request, ::kapa::tarracsh::app::server::digest::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Diff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest* request, ::kapa::tarracsh::app::server::digest::DiffResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Diff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest* request, ::kapa::tarracsh::app::server::digest::DiffResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::Empty>* AsyncQuitRaw(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::Empty>* PrepareAsyncQuitRaw(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::DiffResponse>* AsyncDiffRaw(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kapa::tarracsh::app::server::digest::DiffResponse>* PrepareAsyncDiffRaw(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Quit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::kapa::tarracsh::app::server::digest::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::Empty>> AsyncQuit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::Empty>>(AsyncQuitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::Empty>> PrepareAsyncQuit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::Empty>>(PrepareAsyncQuitRaw(context, request, cq));
    }
    ::grpc::Status Diff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::kapa::tarracsh::app::server::digest::DiffResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::DiffResponse>> AsyncDiff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::DiffResponse>>(AsyncDiffRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::DiffResponse>> PrepareAsyncDiff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::DiffResponse>>(PrepareAsyncDiffRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Quit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty* request, ::kapa::tarracsh::app::server::digest::Empty* response, std::function<void(::grpc::Status)>) override;
      void Quit(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty* request, ::kapa::tarracsh::app::server::digest::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Diff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest* request, ::kapa::tarracsh::app::server::digest::DiffResponse* response, std::function<void(::grpc::Status)>) override;
      void Diff(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest* request, ::kapa::tarracsh::app::server::digest::DiffResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::Empty>* AsyncQuitRaw(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::Empty>* PrepareAsyncQuitRaw(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::DiffResponse>* AsyncDiffRaw(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kapa::tarracsh::app::server::digest::DiffResponse>* PrepareAsyncDiffRaw(::grpc::ClientContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Quit_;
    const ::grpc::internal::RpcMethod rpcmethod_Diff_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Quit(::grpc::ServerContext* context, const ::kapa::tarracsh::app::server::digest::Empty* request, ::kapa::tarracsh::app::server::digest::Empty* response);
    virtual ::grpc::Status Diff(::grpc::ServerContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest* request, ::kapa::tarracsh::app::server::digest::DiffResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Quit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Quit() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Quit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Quit(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::Empty* /*request*/, ::kapa::tarracsh::app::server::digest::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQuit(::grpc::ServerContext* context, ::kapa::tarracsh::app::server::digest::Empty* request, ::grpc::ServerAsyncResponseWriter< ::kapa::tarracsh::app::server::digest::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Diff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Diff() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Diff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Diff(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::DiffRequest* /*request*/, ::kapa::tarracsh::app::server::digest::DiffResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDiff(::grpc::ServerContext* context, ::kapa::tarracsh::app::server::digest::DiffRequest* request, ::grpc::ServerAsyncResponseWriter< ::kapa::tarracsh::app::server::digest::DiffResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Quit<WithAsyncMethod_Diff<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Quit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Quit() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::kapa::tarracsh::app::server::digest::Empty, ::kapa::tarracsh::app::server::digest::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kapa::tarracsh::app::server::digest::Empty* request, ::kapa::tarracsh::app::server::digest::Empty* response) { return this->Quit(context, request, response); }));}
    void SetMessageAllocatorFor_Quit(
        ::grpc::MessageAllocator< ::kapa::tarracsh::app::server::digest::Empty, ::kapa::tarracsh::app::server::digest::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kapa::tarracsh::app::server::digest::Empty, ::kapa::tarracsh::app::server::digest::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Quit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Quit(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::Empty* /*request*/, ::kapa::tarracsh::app::server::digest::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Quit(
      ::grpc::CallbackServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::Empty* /*request*/, ::kapa::tarracsh::app::server::digest::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Diff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Diff() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::kapa::tarracsh::app::server::digest::DiffRequest, ::kapa::tarracsh::app::server::digest::DiffResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kapa::tarracsh::app::server::digest::DiffRequest* request, ::kapa::tarracsh::app::server::digest::DiffResponse* response) { return this->Diff(context, request, response); }));}
    void SetMessageAllocatorFor_Diff(
        ::grpc::MessageAllocator< ::kapa::tarracsh::app::server::digest::DiffRequest, ::kapa::tarracsh::app::server::digest::DiffResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kapa::tarracsh::app::server::digest::DiffRequest, ::kapa::tarracsh::app::server::digest::DiffResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Diff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Diff(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::DiffRequest* /*request*/, ::kapa::tarracsh::app::server::digest::DiffResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Diff(
      ::grpc::CallbackServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::DiffRequest* /*request*/, ::kapa::tarracsh::app::server::digest::DiffResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Quit<WithCallbackMethod_Diff<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Quit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Quit() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Quit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Quit(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::Empty* /*request*/, ::kapa::tarracsh::app::server::digest::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Diff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Diff() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Diff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Diff(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::DiffRequest* /*request*/, ::kapa::tarracsh::app::server::digest::DiffResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Quit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Quit() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Quit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Quit(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::Empty* /*request*/, ::kapa::tarracsh::app::server::digest::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQuit(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Diff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Diff() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Diff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Diff(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::DiffRequest* /*request*/, ::kapa::tarracsh::app::server::digest::DiffResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDiff(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Quit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Quit() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Quit(context, request, response); }));
    }
    ~WithRawCallbackMethod_Quit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Quit(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::Empty* /*request*/, ::kapa::tarracsh::app::server::digest::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Quit(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Diff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Diff() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Diff(context, request, response); }));
    }
    ~WithRawCallbackMethod_Diff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this member
    ::grpc::Status Diff(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::DiffRequest* /*request*/, ::kapa::tarracsh::app::server::digest::DiffResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Diff(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Quit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Quit() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::kapa::tarracsh::app::server::digest::Empty, ::kapa::tarracsh::app::server::digest::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::kapa::tarracsh::app::server::digest::Empty, ::kapa::tarracsh::app::server::digest::Empty>* streamer) {
                       return this->StreamedQuit(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Quit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this member
    ::grpc::Status Quit(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::Empty* /*request*/, ::kapa::tarracsh::app::server::digest::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of member with streamed unary
    virtual ::grpc::Status StreamedQuit(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kapa::tarracsh::app::server::digest::Empty,::kapa::tarracsh::app::server::digest::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Diff : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Diff() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::kapa::tarracsh::app::server::digest::DiffRequest, ::kapa::tarracsh::app::server::digest::DiffResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::kapa::tarracsh::app::server::digest::DiffRequest, ::kapa::tarracsh::app::server::digest::DiffResponse>* streamer) {
                       return this->StreamedDiff(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Diff() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this member
    ::grpc::Status Diff(::grpc::ServerContext* /*context*/, const ::kapa::tarracsh::app::server::digest::DiffRequest* /*request*/, ::kapa::tarracsh::app::server::digest::DiffResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of member with streamed unary
    virtual ::grpc::Status StreamedDiff(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kapa::tarracsh::app::server::digest::DiffRequest,::kapa::tarracsh::app::server::digest::DiffResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Quit<WithStreamedUnaryMethod_Diff<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Quit<WithStreamedUnaryMethod_Diff<Service > > StreamedService;
};

}  // namespace digest
}  // namespace server
}  // namespace app
}  // namespace tarracsh
}  // namespace kapa


#endif  // GRPC_Server_2eproto__INCLUDED
