// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Server.proto
// Protobuf C++ Version: 5.29.5

#include "Server.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace kapa {
namespace tarracsh {
namespace app {
namespace server {
namespace digest {

inline constexpr FileDigestResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        isnew_{false},
        ismodified_{false},
        issamedigest_{false},
        failed_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileDigestResult::FileDigestResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileDigestResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileDigestResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileDigestResultDefaultTypeInternal() {}
  union {
    FileDigestResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileDigestResultDefaultTypeInternal _FileDigestResult_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;

inline constexpr DiffRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : input_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        dryrun_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DiffRequest::DiffRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DiffRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DiffRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DiffRequestDefaultTypeInternal() {}
  union {
    DiffRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DiffRequestDefaultTypeInternal _DiffRequest_default_instance_;

inline constexpr ClassDigestResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : strongclassname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        isnew_{false},
        ismodified_{false},
        issamedigest_{false},
        failed_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClassDigestResult::ClassDigestResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClassDigestResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClassDigestResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClassDigestResultDefaultTypeInternal() {}
  union {
    ClassDigestResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClassDigestResultDefaultTypeInternal _ClassDigestResult_default_instance_;

inline constexpr DiffResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : files_{},
        classfiles_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DiffResponse::DiffResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DiffResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DiffResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DiffResponseDefaultTypeInternal() {}
  union {
    DiffResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DiffResponseDefaultTypeInternal _DiffResponse_default_instance_;
}  // namespace digest
}  // namespace server
}  // namespace app
}  // namespace tarracsh
}  // namespace kapa
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Server_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Server_2eproto = nullptr;
const ::uint32_t
    TableStruct_Server_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::Empty, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::DiffRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::DiffRequest, _impl_.input_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::DiffRequest, _impl_.dryrun_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::FileDigestResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::FileDigestResult, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::FileDigestResult, _impl_.isnew_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::FileDigestResult, _impl_.ismodified_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::FileDigestResult, _impl_.issamedigest_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::FileDigestResult, _impl_.failed_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::ClassDigestResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::ClassDigestResult, _impl_.strongclassname_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::ClassDigestResult, _impl_.isnew_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::ClassDigestResult, _impl_.ismodified_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::ClassDigestResult, _impl_.issamedigest_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::ClassDigestResult, _impl_.failed_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::DiffResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::DiffResponse, _impl_.files_),
        PROTOBUF_FIELD_OFFSET(::kapa::tarracsh::app::server::digest::DiffResponse, _impl_.classfiles_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::kapa::tarracsh::app::server::digest::Empty)},
        {8, -1, -1, sizeof(::kapa::tarracsh::app::server::digest::DiffRequest)},
        {18, -1, -1, sizeof(::kapa::tarracsh::app::server::digest::FileDigestResult)},
        {31, -1, -1, sizeof(::kapa::tarracsh::app::server::digest::ClassDigestResult)},
        {44, -1, -1, sizeof(::kapa::tarracsh::app::server::digest::DiffResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::kapa::tarracsh::app::server::digest::_Empty_default_instance_._instance,
    &::kapa::tarracsh::app::server::digest::_DiffRequest_default_instance_._instance,
    &::kapa::tarracsh::app::server::digest::_FileDigestResult_default_instance_._instance,
    &::kapa::tarracsh::app::server::digest::_ClassDigestResult_default_instance_._instance,
    &::kapa::tarracsh::app::server::digest::_DiffResponse_default_instance_._instance,
};
const char descriptor_table_protodef_Server_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014Server.proto\022\037kapa.tarracsh.app.server"
    ".digest\"\007\n\005Empty\",\n\013DiffRequest\022\r\n\005input"
    "\030\001 \001(\t\022\016\n\006dryRun\030\002 \001(\010\"m\n\020FileDigestResu"
    "lt\022\020\n\010filename\030\001 \001(\t\022\r\n\005isNew\030\002 \001(\010\022\022\n\ni"
    "sModified\030\003 \001(\010\022\024\n\014isSameDigest\030\004 \001(\010\022\016\n"
    "\006failed\030\005 \001(\010\"u\n\021ClassDigestResult\022\027\n\017st"
    "rongClassname\030\001 \001(\t\022\r\n\005isNew\030\002 \001(\010\022\022\n\nis"
    "Modified\030\003 \001(\010\022\024\n\014isSameDigest\030\004 \001(\010\022\016\n\006"
    "failed\030\005 \001(\010\"\230\001\n\014DiffResponse\022@\n\005files\030\001"
    " \003(\01321.kapa.tarracsh.app.server.digest.F"
    "ileDigestResult\022F\n\nclassfiles\030\002 \003(\01322.ka"
    "pa.tarracsh.app.server.digest.ClassDiges"
    "tResult2\317\001\n\014PublicDigest\022X\n\004Quit\022&.kapa."
    "tarracsh.app.server.digest.Empty\032&.kapa."
    "tarracsh.app.server.digest.Empty\"\000\022e\n\004Di"
    "ff\022,.kapa.tarracsh.app.server.digest.Dif"
    "fRequest\032-.kapa.tarracsh.app.server.dige"
    "st.DiffResponse\"\000B6\n\033io.grpc.examples.ro"
    "uteguideB\017RouteGuideProtoP\001\242\002\003RTGb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_Server_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Server_2eproto = {
    false,
    false,
    761,
    descriptor_table_protodef_Server_2eproto,
    "Server.proto",
    &descriptor_table_Server_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_Server_2eproto::offsets,
    file_level_enum_descriptors_Server_2eproto,
    file_level_service_descriptors_Server_2eproto,
};
namespace kapa {
namespace tarracsh {
namespace app {
namespace server {
namespace digest {
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:kapa.tarracsh.app.server.digest.Empty)
}
Empty::Empty(
    ::google::protobuf::Arena* arena,
    const Empty& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:kapa.tarracsh.app.server.digest.Empty)
}

inline void* Empty::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Empty(arena);
}
constexpr auto Empty::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Empty),
                                            alignof(Empty));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Empty::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Empty_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Empty::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Empty>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Empty::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Empty>(), &Empty::ByteSizeLong,
            &Empty::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Empty, _impl_._cached_size_),
        false,
    },
    &Empty::kDescriptorMethods,
    &descriptor_table_Server_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Empty::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> Empty::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kapa::tarracsh::app::server::digest::Empty>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata Empty::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DiffRequest::_Internal {
 public:
};

DiffRequest::DiffRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kapa.tarracsh.app.server.digest.DiffRequest)
}
inline PROTOBUF_NDEBUG_INLINE DiffRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kapa::tarracsh::app::server::digest::DiffRequest& from_msg)
      : input_(arena, from.input_),
        _cached_size_{0} {}

DiffRequest::DiffRequest(
    ::google::protobuf::Arena* arena,
    const DiffRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DiffRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.dryrun_ = from._impl_.dryrun_;

  // @@protoc_insertion_point(copy_constructor:kapa.tarracsh.app.server.digest.DiffRequest)
}
inline PROTOBUF_NDEBUG_INLINE DiffRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : input_(arena),
        _cached_size_{0} {}

inline void DiffRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.dryrun_ = {};
}
DiffRequest::~DiffRequest() {
  // @@protoc_insertion_point(destructor:kapa.tarracsh.app.server.digest.DiffRequest)
  SharedDtor(*this);
}
inline void DiffRequest::SharedDtor(MessageLite& self) {
  DiffRequest& this_ = static_cast<DiffRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.input_.Destroy();
  this_._impl_.~Impl_();
}

inline void* DiffRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DiffRequest(arena);
}
constexpr auto DiffRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DiffRequest),
                                            alignof(DiffRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DiffRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DiffRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DiffRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DiffRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DiffRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DiffRequest>(), &DiffRequest::ByteSizeLong,
            &DiffRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DiffRequest, _impl_._cached_size_),
        false,
    },
    &DiffRequest::kDescriptorMethods,
    &descriptor_table_Server_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DiffRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 57, 2> DiffRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kapa::tarracsh::app::server::digest::DiffRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool dryRun = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(DiffRequest, _impl_.dryrun_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DiffRequest, _impl_.dryrun_)}},
    // string input = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DiffRequest, _impl_.input_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string input = 1;
    {PROTOBUF_FIELD_OFFSET(DiffRequest, _impl_.input_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool dryRun = 2;
    {PROTOBUF_FIELD_OFFSET(DiffRequest, _impl_.dryrun_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\53\5\0\0\0\0\0\0"
    "kapa.tarracsh.app.server.digest.DiffRequest"
    "input"
  }},
};

PROTOBUF_NOINLINE void DiffRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:kapa.tarracsh.app.server.digest.DiffRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.input_.ClearToEmpty();
  _impl_.dryrun_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DiffRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DiffRequest& this_ = static_cast<const DiffRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DiffRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DiffRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kapa.tarracsh.app.server.digest.DiffRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string input = 1;
          if (!this_._internal_input().empty()) {
            const std::string& _s = this_._internal_input();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kapa.tarracsh.app.server.digest.DiffRequest.input");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool dryRun = 2;
          if (this_._internal_dryrun() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_dryrun(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kapa.tarracsh.app.server.digest.DiffRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DiffRequest::ByteSizeLong(const MessageLite& base) {
          const DiffRequest& this_ = static_cast<const DiffRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DiffRequest::ByteSizeLong() const {
          const DiffRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kapa.tarracsh.app.server.digest.DiffRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string input = 1;
            if (!this_._internal_input().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_input());
            }
            // bool dryRun = 2;
            if (this_._internal_dryrun() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DiffRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DiffRequest*>(&to_msg);
  auto& from = static_cast<const DiffRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kapa.tarracsh.app.server.digest.DiffRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_input().empty()) {
    _this->_internal_set_input(from._internal_input());
  }
  if (from._internal_dryrun() != 0) {
    _this->_impl_.dryrun_ = from._impl_.dryrun_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DiffRequest::CopyFrom(const DiffRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kapa.tarracsh.app.server.digest.DiffRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DiffRequest::InternalSwap(DiffRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.input_, &other->_impl_.input_, arena);
        swap(_impl_.dryrun_, other->_impl_.dryrun_);
}

::google::protobuf::Metadata DiffRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileDigestResult::_Internal {
 public:
};

FileDigestResult::FileDigestResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kapa.tarracsh.app.server.digest.FileDigestResult)
}
inline PROTOBUF_NDEBUG_INLINE FileDigestResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kapa::tarracsh::app::server::digest::FileDigestResult& from_msg)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

FileDigestResult::FileDigestResult(
    ::google::protobuf::Arena* arena,
    const FileDigestResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileDigestResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isnew_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, isnew_),
           offsetof(Impl_, failed_) -
               offsetof(Impl_, isnew_) +
               sizeof(Impl_::failed_));

  // @@protoc_insertion_point(copy_constructor:kapa.tarracsh.app.server.digest.FileDigestResult)
}
inline PROTOBUF_NDEBUG_INLINE FileDigestResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void FileDigestResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isnew_),
           0,
           offsetof(Impl_, failed_) -
               offsetof(Impl_, isnew_) +
               sizeof(Impl_::failed_));
}
FileDigestResult::~FileDigestResult() {
  // @@protoc_insertion_point(destructor:kapa.tarracsh.app.server.digest.FileDigestResult)
  SharedDtor(*this);
}
inline void FileDigestResult::SharedDtor(MessageLite& self) {
  FileDigestResult& this_ = static_cast<FileDigestResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* FileDigestResult::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FileDigestResult(arena);
}
constexpr auto FileDigestResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileDigestResult),
                                            alignof(FileDigestResult));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FileDigestResult::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FileDigestResult_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FileDigestResult::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FileDigestResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FileDigestResult::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FileDigestResult>(), &FileDigestResult::ByteSizeLong,
            &FileDigestResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_._cached_size_),
        false,
    },
    &FileDigestResult::kDescriptorMethods,
    &descriptor_table_Server_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FileDigestResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 65, 2> FileDigestResult::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kapa::tarracsh::app::server::digest::FileDigestResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.filename_)}},
    // bool isNew = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileDigestResult, _impl_.isnew_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.isnew_)}},
    // bool isModified = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileDigestResult, _impl_.ismodified_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.ismodified_)}},
    // bool isSameDigest = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileDigestResult, _impl_.issamedigest_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.issamedigest_)}},
    // bool failed = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileDigestResult, _impl_.failed_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.failed_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool isNew = 2;
    {PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.isnew_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool isModified = 3;
    {PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.ismodified_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool isSameDigest = 4;
    {PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.issamedigest_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool failed = 5;
    {PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.failed_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\60\10\0\0\0\0\0\0"
    "kapa.tarracsh.app.server.digest.FileDigestResult"
    "filename"
  }},
};

PROTOBUF_NOINLINE void FileDigestResult::Clear() {
// @@protoc_insertion_point(message_clear_start:kapa.tarracsh.app.server.digest.FileDigestResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  ::memset(&_impl_.isnew_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.failed_) -
      reinterpret_cast<char*>(&_impl_.isnew_)) + sizeof(_impl_.failed_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FileDigestResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FileDigestResult& this_ = static_cast<const FileDigestResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FileDigestResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FileDigestResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kapa.tarracsh.app.server.digest.FileDigestResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string filename = 1;
          if (!this_._internal_filename().empty()) {
            const std::string& _s = this_._internal_filename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kapa.tarracsh.app.server.digest.FileDigestResult.filename");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool isNew = 2;
          if (this_._internal_isnew() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_isnew(), target);
          }

          // bool isModified = 3;
          if (this_._internal_ismodified() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_ismodified(), target);
          }

          // bool isSameDigest = 4;
          if (this_._internal_issamedigest() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_issamedigest(), target);
          }

          // bool failed = 5;
          if (this_._internal_failed() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_failed(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kapa.tarracsh.app.server.digest.FileDigestResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FileDigestResult::ByteSizeLong(const MessageLite& base) {
          const FileDigestResult& this_ = static_cast<const FileDigestResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FileDigestResult::ByteSizeLong() const {
          const FileDigestResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kapa.tarracsh.app.server.digest.FileDigestResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string filename = 1;
            if (!this_._internal_filename().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_filename());
            }
            // bool isNew = 2;
            if (this_._internal_isnew() != 0) {
              total_size += 2;
            }
            // bool isModified = 3;
            if (this_._internal_ismodified() != 0) {
              total_size += 2;
            }
            // bool isSameDigest = 4;
            if (this_._internal_issamedigest() != 0) {
              total_size += 2;
            }
            // bool failed = 5;
            if (this_._internal_failed() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FileDigestResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileDigestResult*>(&to_msg);
  auto& from = static_cast<const FileDigestResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kapa.tarracsh.app.server.digest.FileDigestResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_isnew() != 0) {
    _this->_impl_.isnew_ = from._impl_.isnew_;
  }
  if (from._internal_ismodified() != 0) {
    _this->_impl_.ismodified_ = from._impl_.ismodified_;
  }
  if (from._internal_issamedigest() != 0) {
    _this->_impl_.issamedigest_ = from._impl_.issamedigest_;
  }
  if (from._internal_failed() != 0) {
    _this->_impl_.failed_ = from._impl_.failed_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileDigestResult::CopyFrom(const FileDigestResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kapa.tarracsh.app.server.digest.FileDigestResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileDigestResult::InternalSwap(FileDigestResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.failed_)
      + sizeof(FileDigestResult::_impl_.failed_)
      - PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.isnew_)>(
          reinterpret_cast<char*>(&_impl_.isnew_),
          reinterpret_cast<char*>(&other->_impl_.isnew_));
}

::google::protobuf::Metadata FileDigestResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ClassDigestResult::_Internal {
 public:
};

ClassDigestResult::ClassDigestResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kapa.tarracsh.app.server.digest.ClassDigestResult)
}
inline PROTOBUF_NDEBUG_INLINE ClassDigestResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kapa::tarracsh::app::server::digest::ClassDigestResult& from_msg)
      : strongclassname_(arena, from.strongclassname_),
        _cached_size_{0} {}

ClassDigestResult::ClassDigestResult(
    ::google::protobuf::Arena* arena,
    const ClassDigestResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ClassDigestResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isnew_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, isnew_),
           offsetof(Impl_, failed_) -
               offsetof(Impl_, isnew_) +
               sizeof(Impl_::failed_));

  // @@protoc_insertion_point(copy_constructor:kapa.tarracsh.app.server.digest.ClassDigestResult)
}
inline PROTOBUF_NDEBUG_INLINE ClassDigestResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : strongclassname_(arena),
        _cached_size_{0} {}

inline void ClassDigestResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isnew_),
           0,
           offsetof(Impl_, failed_) -
               offsetof(Impl_, isnew_) +
               sizeof(Impl_::failed_));
}
ClassDigestResult::~ClassDigestResult() {
  // @@protoc_insertion_point(destructor:kapa.tarracsh.app.server.digest.ClassDigestResult)
  SharedDtor(*this);
}
inline void ClassDigestResult::SharedDtor(MessageLite& self) {
  ClassDigestResult& this_ = static_cast<ClassDigestResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.strongclassname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ClassDigestResult::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ClassDigestResult(arena);
}
constexpr auto ClassDigestResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ClassDigestResult),
                                            alignof(ClassDigestResult));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ClassDigestResult::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ClassDigestResult_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ClassDigestResult::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ClassDigestResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ClassDigestResult::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ClassDigestResult>(), &ClassDigestResult::ByteSizeLong,
            &ClassDigestResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_._cached_size_),
        false,
    },
    &ClassDigestResult::kDescriptorMethods,
    &descriptor_table_Server_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ClassDigestResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 73, 2> ClassDigestResult::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kapa::tarracsh::app::server::digest::ClassDigestResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string strongClassname = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.strongclassname_)}},
    // bool isNew = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ClassDigestResult, _impl_.isnew_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.isnew_)}},
    // bool isModified = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ClassDigestResult, _impl_.ismodified_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.ismodified_)}},
    // bool isSameDigest = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ClassDigestResult, _impl_.issamedigest_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.issamedigest_)}},
    // bool failed = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ClassDigestResult, _impl_.failed_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.failed_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string strongClassname = 1;
    {PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.strongclassname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool isNew = 2;
    {PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.isnew_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool isModified = 3;
    {PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.ismodified_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool isSameDigest = 4;
    {PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.issamedigest_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool failed = 5;
    {PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.failed_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\61\17\0\0\0\0\0\0"
    "kapa.tarracsh.app.server.digest.ClassDigestResult"
    "strongClassname"
  }},
};

PROTOBUF_NOINLINE void ClassDigestResult::Clear() {
// @@protoc_insertion_point(message_clear_start:kapa.tarracsh.app.server.digest.ClassDigestResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.strongclassname_.ClearToEmpty();
  ::memset(&_impl_.isnew_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.failed_) -
      reinterpret_cast<char*>(&_impl_.isnew_)) + sizeof(_impl_.failed_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ClassDigestResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ClassDigestResult& this_ = static_cast<const ClassDigestResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ClassDigestResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ClassDigestResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kapa.tarracsh.app.server.digest.ClassDigestResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string strongClassname = 1;
          if (!this_._internal_strongclassname().empty()) {
            const std::string& _s = this_._internal_strongclassname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kapa.tarracsh.app.server.digest.ClassDigestResult.strongClassname");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool isNew = 2;
          if (this_._internal_isnew() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_isnew(), target);
          }

          // bool isModified = 3;
          if (this_._internal_ismodified() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_ismodified(), target);
          }

          // bool isSameDigest = 4;
          if (this_._internal_issamedigest() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_issamedigest(), target);
          }

          // bool failed = 5;
          if (this_._internal_failed() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_failed(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kapa.tarracsh.app.server.digest.ClassDigestResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ClassDigestResult::ByteSizeLong(const MessageLite& base) {
          const ClassDigestResult& this_ = static_cast<const ClassDigestResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ClassDigestResult::ByteSizeLong() const {
          const ClassDigestResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kapa.tarracsh.app.server.digest.ClassDigestResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string strongClassname = 1;
            if (!this_._internal_strongclassname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_strongclassname());
            }
            // bool isNew = 2;
            if (this_._internal_isnew() != 0) {
              total_size += 2;
            }
            // bool isModified = 3;
            if (this_._internal_ismodified() != 0) {
              total_size += 2;
            }
            // bool isSameDigest = 4;
            if (this_._internal_issamedigest() != 0) {
              total_size += 2;
            }
            // bool failed = 5;
            if (this_._internal_failed() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ClassDigestResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ClassDigestResult*>(&to_msg);
  auto& from = static_cast<const ClassDigestResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kapa.tarracsh.app.server.digest.ClassDigestResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_strongclassname().empty()) {
    _this->_internal_set_strongclassname(from._internal_strongclassname());
  }
  if (from._internal_isnew() != 0) {
    _this->_impl_.isnew_ = from._impl_.isnew_;
  }
  if (from._internal_ismodified() != 0) {
    _this->_impl_.ismodified_ = from._impl_.ismodified_;
  }
  if (from._internal_issamedigest() != 0) {
    _this->_impl_.issamedigest_ = from._impl_.issamedigest_;
  }
  if (from._internal_failed() != 0) {
    _this->_impl_.failed_ = from._impl_.failed_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClassDigestResult::CopyFrom(const ClassDigestResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kapa.tarracsh.app.server.digest.ClassDigestResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ClassDigestResult::InternalSwap(ClassDigestResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.strongclassname_, &other->_impl_.strongclassname_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.failed_)
      + sizeof(ClassDigestResult::_impl_.failed_)
      - PROTOBUF_FIELD_OFFSET(ClassDigestResult, _impl_.isnew_)>(
          reinterpret_cast<char*>(&_impl_.isnew_),
          reinterpret_cast<char*>(&other->_impl_.isnew_));
}

::google::protobuf::Metadata ClassDigestResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DiffResponse::_Internal {
 public:
};

DiffResponse::DiffResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kapa.tarracsh.app.server.digest.DiffResponse)
}
inline PROTOBUF_NDEBUG_INLINE DiffResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::kapa::tarracsh::app::server::digest::DiffResponse& from_msg)
      : files_{visibility, arena, from.files_},
        classfiles_{visibility, arena, from.classfiles_},
        _cached_size_{0} {}

DiffResponse::DiffResponse(
    ::google::protobuf::Arena* arena,
    const DiffResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DiffResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:kapa.tarracsh.app.server.digest.DiffResponse)
}
inline PROTOBUF_NDEBUG_INLINE DiffResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : files_{visibility, arena},
        classfiles_{visibility, arena},
        _cached_size_{0} {}

inline void DiffResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DiffResponse::~DiffResponse() {
  // @@protoc_insertion_point(destructor:kapa.tarracsh.app.server.digest.DiffResponse)
  SharedDtor(*this);
}
inline void DiffResponse::SharedDtor(MessageLite& self) {
  DiffResponse& this_ = static_cast<DiffResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* DiffResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DiffResponse(arena);
}
constexpr auto DiffResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(DiffResponse, _impl_.files_) +
          decltype(DiffResponse::_impl_.files_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(DiffResponse, _impl_.classfiles_) +
          decltype(DiffResponse::_impl_.classfiles_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(DiffResponse), alignof(DiffResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&DiffResponse::PlacementNew_,
                                 sizeof(DiffResponse),
                                 alignof(DiffResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DiffResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DiffResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DiffResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DiffResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DiffResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DiffResponse>(), &DiffResponse::ByteSizeLong,
            &DiffResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DiffResponse, _impl_._cached_size_),
        false,
    },
    &DiffResponse::kDescriptorMethods,
    &descriptor_table_Server_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DiffResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> DiffResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::kapa::tarracsh::app::server::digest::DiffResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .kapa.tarracsh.app.server.digest.ClassDigestResult classfiles = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(DiffResponse, _impl_.classfiles_)}},
    // repeated .kapa.tarracsh.app.server.digest.FileDigestResult files = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DiffResponse, _impl_.files_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .kapa.tarracsh.app.server.digest.FileDigestResult files = 1;
    {PROTOBUF_FIELD_OFFSET(DiffResponse, _impl_.files_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .kapa.tarracsh.app.server.digest.ClassDigestResult classfiles = 2;
    {PROTOBUF_FIELD_OFFSET(DiffResponse, _impl_.classfiles_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::kapa::tarracsh::app::server::digest::FileDigestResult>()},
    {::_pbi::TcParser::GetTable<::kapa::tarracsh::app::server::digest::ClassDigestResult>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void DiffResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:kapa.tarracsh.app.server.digest.DiffResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.files_.Clear();
  _impl_.classfiles_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DiffResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DiffResponse& this_ = static_cast<const DiffResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DiffResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DiffResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:kapa.tarracsh.app.server.digest.DiffResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .kapa.tarracsh.app.server.digest.FileDigestResult files = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_files_size());
               i < n; i++) {
            const auto& repfield = this_._internal_files().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated .kapa.tarracsh.app.server.digest.ClassDigestResult classfiles = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_classfiles_size());
               i < n; i++) {
            const auto& repfield = this_._internal_classfiles().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:kapa.tarracsh.app.server.digest.DiffResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DiffResponse::ByteSizeLong(const MessageLite& base) {
          const DiffResponse& this_ = static_cast<const DiffResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DiffResponse::ByteSizeLong() const {
          const DiffResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:kapa.tarracsh.app.server.digest.DiffResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .kapa.tarracsh.app.server.digest.FileDigestResult files = 1;
            {
              total_size += 1UL * this_._internal_files_size();
              for (const auto& msg : this_._internal_files()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated .kapa.tarracsh.app.server.digest.ClassDigestResult classfiles = 2;
            {
              total_size += 1UL * this_._internal_classfiles_size();
              for (const auto& msg : this_._internal_classfiles()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DiffResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DiffResponse*>(&to_msg);
  auto& from = static_cast<const DiffResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kapa.tarracsh.app.server.digest.DiffResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_files()->MergeFrom(
      from._internal_files());
  _this->_internal_mutable_classfiles()->MergeFrom(
      from._internal_classfiles());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DiffResponse::CopyFrom(const DiffResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kapa.tarracsh.app.server.digest.DiffResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DiffResponse::InternalSwap(DiffResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.files_.InternalSwap(&other->_impl_.files_);
  _impl_.classfiles_.InternalSwap(&other->_impl_.classfiles_);
}

::google::protobuf::Metadata DiffResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace digest
}  // namespace server
}  // namespace app
}  // namespace tarracsh
}  // namespace kapa
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Server_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
