// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Server.proto
// Protobuf C++ Version: 5.29.5

#ifndef Server_2eproto_2epb_2eh
#define Server_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Server_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Server_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Server_2eproto;
namespace kapa {
namespace tarracsh {
namespace app {
namespace server {
namespace digest {
class ClassDigestResult;
struct ClassDigestResultDefaultTypeInternal;
extern ClassDigestResultDefaultTypeInternal _ClassDigestResult_default_instance_;
class DiffRequest;
struct DiffRequestDefaultTypeInternal;
extern DiffRequestDefaultTypeInternal _DiffRequest_default_instance_;
class DiffResponse;
struct DiffResponseDefaultTypeInternal;
extern DiffResponseDefaultTypeInternal _DiffResponse_default_instance_;
class Empty;
struct EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class FileDigestResult;
struct FileDigestResultDefaultTypeInternal;
extern FileDigestResultDefaultTypeInternal _FileDigestResult_default_instance_;
}  // namespace digest
}  // namespace server
}  // namespace app
}  // namespace tarracsh
}  // namespace kapa
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace kapa {
namespace tarracsh {
namespace app {
namespace server {
namespace digest {

// ===================================================================


// -------------------------------------------------------------------

class FileDigestResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kapa.tarracsh.app.server.digest.FileDigestResult) */ {
 public:
  inline FileDigestResult() : FileDigestResult(nullptr) {}
  ~FileDigestResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileDigestResult* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileDigestResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileDigestResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline FileDigestResult(const FileDigestResult& from) : FileDigestResult(nullptr, from) {}
  inline FileDigestResult(FileDigestResult&& from) noexcept
      : FileDigestResult(nullptr, std::move(from)) {}
  inline FileDigestResult& operator=(const FileDigestResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileDigestResult& operator=(FileDigestResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileDigestResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileDigestResult* internal_default_instance() {
    return reinterpret_cast<const FileDigestResult*>(
        &_FileDigestResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(FileDigestResult& a, FileDigestResult& b) { a.Swap(&b); }
  inline void Swap(FileDigestResult* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileDigestResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileDigestResult* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileDigestResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileDigestResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileDigestResult& from) { FileDigestResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileDigestResult* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kapa.tarracsh.app.server.digest.FileDigestResult"; }

 protected:
  explicit FileDigestResult(::google::protobuf::Arena* arena);
  FileDigestResult(::google::protobuf::Arena* arena, const FileDigestResult& from);
  FileDigestResult(::google::protobuf::Arena* arena, FileDigestResult&& from) noexcept
      : FileDigestResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilenameFieldNumber = 1,
    kIsNewFieldNumber = 2,
    kIsModifiedFieldNumber = 3,
    kIsSameDigestFieldNumber = 4,
    kFailedFieldNumber = 5,
  };
  // string filename = 1;
  void clear_filename() ;
  const std::string& filename() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* value);

  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(
      const std::string& value);
  std::string* _internal_mutable_filename();

  public:
  // bool isNew = 2;
  void clear_isnew() ;
  bool isnew() const;
  void set_isnew(bool value);

  private:
  bool _internal_isnew() const;
  void _internal_set_isnew(bool value);

  public:
  // bool isModified = 3;
  void clear_ismodified() ;
  bool ismodified() const;
  void set_ismodified(bool value);

  private:
  bool _internal_ismodified() const;
  void _internal_set_ismodified(bool value);

  public:
  // bool isSameDigest = 4;
  void clear_issamedigest() ;
  bool issamedigest() const;
  void set_issamedigest(bool value);

  private:
  bool _internal_issamedigest() const;
  void _internal_set_issamedigest(bool value);

  public:
  // bool failed = 5;
  void clear_failed() ;
  bool failed() const;
  void set_failed(bool value);

  private:
  bool _internal_failed() const;
  void _internal_set_failed(bool value);

  public:
  // @@protoc_insertion_point(class_scope:kapa.tarracsh.app.server.digest.FileDigestResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      65, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const FileDigestResult& from_msg);
    ::google::protobuf::internal::ArenaStringPtr filename_;
    bool isnew_;
    bool ismodified_;
    bool issamedigest_;
    bool failed_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Server_2eproto;
};
// -------------------------------------------------------------------

class Empty final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:kapa.tarracsh.app.server.digest.Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Empty* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Empty));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Empty(
      ::google::protobuf::internal::ConstantInitialized);

  inline Empty(const Empty& from) : Empty(nullptr, from) {}
  inline Empty(Empty&& from) noexcept
      : Empty(nullptr, std::move(from)) {}
  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Empty& default_instance() {
    return *internal_default_instance();
  }
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
        &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Empty& a, Empty& b) { a.Swap(&b); }
  inline void Swap(Empty* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Empty* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<Empty>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Empty& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Empty& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kapa.tarracsh.app.server.digest.Empty"; }

 protected:
  explicit Empty(::google::protobuf::Arena* arena);
  Empty(::google::protobuf::Arena* arena, const Empty& from);
  Empty(::google::protobuf::Arena* arena, Empty&& from) noexcept
      : Empty(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:kapa.tarracsh.app.server.digest.Empty)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Empty& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_Server_2eproto;
};
// -------------------------------------------------------------------

class DiffRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kapa.tarracsh.app.server.digest.DiffRequest) */ {
 public:
  inline DiffRequest() : DiffRequest(nullptr) {}
  ~DiffRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DiffRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DiffRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DiffRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline DiffRequest(const DiffRequest& from) : DiffRequest(nullptr, from) {}
  inline DiffRequest(DiffRequest&& from) noexcept
      : DiffRequest(nullptr, std::move(from)) {}
  inline DiffRequest& operator=(const DiffRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiffRequest& operator=(DiffRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiffRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DiffRequest* internal_default_instance() {
    return reinterpret_cast<const DiffRequest*>(
        &_DiffRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(DiffRequest& a, DiffRequest& b) { a.Swap(&b); }
  inline void Swap(DiffRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiffRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiffRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DiffRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DiffRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DiffRequest& from) { DiffRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DiffRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kapa.tarracsh.app.server.digest.DiffRequest"; }

 protected:
  explicit DiffRequest(::google::protobuf::Arena* arena);
  DiffRequest(::google::protobuf::Arena* arena, const DiffRequest& from);
  DiffRequest(::google::protobuf::Arena* arena, DiffRequest&& from) noexcept
      : DiffRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kInputFieldNumber = 1,
    kDryRunFieldNumber = 2,
  };
  // string input = 1;
  void clear_input() ;
  const std::string& input() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_input(Arg_&& arg, Args_... args);
  std::string* mutable_input();
  PROTOBUF_NODISCARD std::string* release_input();
  void set_allocated_input(std::string* value);

  private:
  const std::string& _internal_input() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_input(
      const std::string& value);
  std::string* _internal_mutable_input();

  public:
  // bool dryRun = 2;
  void clear_dryrun() ;
  bool dryrun() const;
  void set_dryrun(bool value);

  private:
  bool _internal_dryrun() const;
  void _internal_set_dryrun(bool value);

  public:
  // @@protoc_insertion_point(class_scope:kapa.tarracsh.app.server.digest.DiffRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      57, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DiffRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr input_;
    bool dryrun_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Server_2eproto;
};
// -------------------------------------------------------------------

class ClassDigestResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kapa.tarracsh.app.server.digest.ClassDigestResult) */ {
 public:
  inline ClassDigestResult() : ClassDigestResult(nullptr) {}
  ~ClassDigestResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ClassDigestResult* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ClassDigestResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ClassDigestResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline ClassDigestResult(const ClassDigestResult& from) : ClassDigestResult(nullptr, from) {}
  inline ClassDigestResult(ClassDigestResult&& from) noexcept
      : ClassDigestResult(nullptr, std::move(from)) {}
  inline ClassDigestResult& operator=(const ClassDigestResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClassDigestResult& operator=(ClassDigestResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClassDigestResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClassDigestResult* internal_default_instance() {
    return reinterpret_cast<const ClassDigestResult*>(
        &_ClassDigestResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ClassDigestResult& a, ClassDigestResult& b) { a.Swap(&b); }
  inline void Swap(ClassDigestResult* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClassDigestResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClassDigestResult* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ClassDigestResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ClassDigestResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ClassDigestResult& from) { ClassDigestResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ClassDigestResult* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kapa.tarracsh.app.server.digest.ClassDigestResult"; }

 protected:
  explicit ClassDigestResult(::google::protobuf::Arena* arena);
  ClassDigestResult(::google::protobuf::Arena* arena, const ClassDigestResult& from);
  ClassDigestResult(::google::protobuf::Arena* arena, ClassDigestResult&& from) noexcept
      : ClassDigestResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStrongClassnameFieldNumber = 1,
    kIsNewFieldNumber = 2,
    kIsModifiedFieldNumber = 3,
    kIsSameDigestFieldNumber = 4,
    kFailedFieldNumber = 5,
  };
  // string strongClassname = 1;
  void clear_strongclassname() ;
  const std::string& strongclassname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_strongclassname(Arg_&& arg, Args_... args);
  std::string* mutable_strongclassname();
  PROTOBUF_NODISCARD std::string* release_strongclassname();
  void set_allocated_strongclassname(std::string* value);

  private:
  const std::string& _internal_strongclassname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_strongclassname(
      const std::string& value);
  std::string* _internal_mutable_strongclassname();

  public:
  // bool isNew = 2;
  void clear_isnew() ;
  bool isnew() const;
  void set_isnew(bool value);

  private:
  bool _internal_isnew() const;
  void _internal_set_isnew(bool value);

  public:
  // bool isModified = 3;
  void clear_ismodified() ;
  bool ismodified() const;
  void set_ismodified(bool value);

  private:
  bool _internal_ismodified() const;
  void _internal_set_ismodified(bool value);

  public:
  // bool isSameDigest = 4;
  void clear_issamedigest() ;
  bool issamedigest() const;
  void set_issamedigest(bool value);

  private:
  bool _internal_issamedigest() const;
  void _internal_set_issamedigest(bool value);

  public:
  // bool failed = 5;
  void clear_failed() ;
  bool failed() const;
  void set_failed(bool value);

  private:
  bool _internal_failed() const;
  void _internal_set_failed(bool value);

  public:
  // @@protoc_insertion_point(class_scope:kapa.tarracsh.app.server.digest.ClassDigestResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      73, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ClassDigestResult& from_msg);
    ::google::protobuf::internal::ArenaStringPtr strongclassname_;
    bool isnew_;
    bool ismodified_;
    bool issamedigest_;
    bool failed_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Server_2eproto;
};
// -------------------------------------------------------------------

class DiffResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:kapa.tarracsh.app.server.digest.DiffResponse) */ {
 public:
  inline DiffResponse() : DiffResponse(nullptr) {}
  ~DiffResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DiffResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DiffResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DiffResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline DiffResponse(const DiffResponse& from) : DiffResponse(nullptr, from) {}
  inline DiffResponse(DiffResponse&& from) noexcept
      : DiffResponse(nullptr, std::move(from)) {}
  inline DiffResponse& operator=(const DiffResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DiffResponse& operator=(DiffResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DiffResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DiffResponse* internal_default_instance() {
    return reinterpret_cast<const DiffResponse*>(
        &_DiffResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(DiffResponse& a, DiffResponse& b) { a.Swap(&b); }
  inline void Swap(DiffResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DiffResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DiffResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DiffResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DiffResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DiffResponse& from) { DiffResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DiffResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "kapa.tarracsh.app.server.digest.DiffResponse"; }

 protected:
  explicit DiffResponse(::google::protobuf::Arena* arena);
  DiffResponse(::google::protobuf::Arena* arena, const DiffResponse& from);
  DiffResponse(::google::protobuf::Arena* arena, DiffResponse&& from) noexcept
      : DiffResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilesFieldNumber = 1,
    kClassfilesFieldNumber = 2,
  };
  // repeated .kapa.tarracsh.app.server.digest.FileDigestResult files = 1;
  int files_size() const;
  private:
  int _internal_files_size() const;

  public:
  void clear_files() ;
  ::kapa::tarracsh::app::server::digest::FileDigestResult* mutable_files(int index);
  ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::FileDigestResult>* mutable_files();

  private:
  const ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::FileDigestResult>& _internal_files() const;
  ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::FileDigestResult>* _internal_mutable_files();
  public:
  const ::kapa::tarracsh::app::server::digest::FileDigestResult& files(int index) const;
  ::kapa::tarracsh::app::server::digest::FileDigestResult* add_files();
  const ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::FileDigestResult>& files() const;
  // repeated .kapa.tarracsh.app.server.digest.ClassDigestResult classfiles = 2;
  int classfiles_size() const;
  private:
  int _internal_classfiles_size() const;

  public:
  void clear_classfiles() ;
  ::kapa::tarracsh::app::server::digest::ClassDigestResult* mutable_classfiles(int index);
  ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::ClassDigestResult>* mutable_classfiles();

  private:
  const ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::ClassDigestResult>& _internal_classfiles() const;
  ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::ClassDigestResult>* _internal_mutable_classfiles();
  public:
  const ::kapa::tarracsh::app::server::digest::ClassDigestResult& classfiles(int index) const;
  ::kapa::tarracsh::app::server::digest::ClassDigestResult* add_classfiles();
  const ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::ClassDigestResult>& classfiles() const;
  // @@protoc_insertion_point(class_scope:kapa.tarracsh.app.server.digest.DiffResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 2,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DiffResponse& from_msg);
    ::google::protobuf::RepeatedPtrField< ::kapa::tarracsh::app::server::digest::FileDigestResult > files_;
    ::google::protobuf::RepeatedPtrField< ::kapa::tarracsh::app::server::digest::ClassDigestResult > classfiles_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Server_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Empty

// -------------------------------------------------------------------

// DiffRequest

// string input = 1;
inline void DiffRequest::clear_input() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_.ClearToEmpty();
}
inline const std::string& DiffRequest::input() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.DiffRequest.input)
  return _internal_input();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DiffRequest::set_input(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.DiffRequest.input)
}
inline std::string* DiffRequest::mutable_input() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_input();
  // @@protoc_insertion_point(field_mutable:kapa.tarracsh.app.server.digest.DiffRequest.input)
  return _s;
}
inline const std::string& DiffRequest::_internal_input() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.input_.Get();
}
inline void DiffRequest::_internal_set_input(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_.Set(value, GetArena());
}
inline std::string* DiffRequest::_internal_mutable_input() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.input_.Mutable( GetArena());
}
inline std::string* DiffRequest::release_input() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kapa.tarracsh.app.server.digest.DiffRequest.input)
  return _impl_.input_.Release();
}
inline void DiffRequest::set_allocated_input(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.input_.IsDefault()) {
    _impl_.input_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kapa.tarracsh.app.server.digest.DiffRequest.input)
}

// bool dryRun = 2;
inline void DiffRequest::clear_dryrun() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dryrun_ = false;
}
inline bool DiffRequest::dryrun() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.DiffRequest.dryRun)
  return _internal_dryrun();
}
inline void DiffRequest::set_dryrun(bool value) {
  _internal_set_dryrun(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.DiffRequest.dryRun)
}
inline bool DiffRequest::_internal_dryrun() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dryrun_;
}
inline void DiffRequest::_internal_set_dryrun(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dryrun_ = value;
}

// -------------------------------------------------------------------

// FileDigestResult

// string filename = 1;
inline void FileDigestResult::clear_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.ClearToEmpty();
}
inline const std::string& FileDigestResult::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.FileDigestResult.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void FileDigestResult::set_filename(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.FileDigestResult.filename)
}
inline std::string* FileDigestResult::mutable_filename() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:kapa.tarracsh.app.server.digest.FileDigestResult.filename)
  return _s;
}
inline const std::string& FileDigestResult::_internal_filename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filename_.Get();
}
inline void FileDigestResult::_internal_set_filename(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.Set(value, GetArena());
}
inline std::string* FileDigestResult::_internal_mutable_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.filename_.Mutable( GetArena());
}
inline std::string* FileDigestResult::release_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kapa.tarracsh.app.server.digest.FileDigestResult.filename)
  return _impl_.filename_.Release();
}
inline void FileDigestResult::set_allocated_filename(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kapa.tarracsh.app.server.digest.FileDigestResult.filename)
}

// bool isNew = 2;
inline void FileDigestResult::clear_isnew() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isnew_ = false;
}
inline bool FileDigestResult::isnew() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.FileDigestResult.isNew)
  return _internal_isnew();
}
inline void FileDigestResult::set_isnew(bool value) {
  _internal_set_isnew(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.FileDigestResult.isNew)
}
inline bool FileDigestResult::_internal_isnew() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isnew_;
}
inline void FileDigestResult::_internal_set_isnew(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isnew_ = value;
}

// bool isModified = 3;
inline void FileDigestResult::clear_ismodified() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ismodified_ = false;
}
inline bool FileDigestResult::ismodified() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.FileDigestResult.isModified)
  return _internal_ismodified();
}
inline void FileDigestResult::set_ismodified(bool value) {
  _internal_set_ismodified(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.FileDigestResult.isModified)
}
inline bool FileDigestResult::_internal_ismodified() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ismodified_;
}
inline void FileDigestResult::_internal_set_ismodified(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ismodified_ = value;
}

// bool isSameDigest = 4;
inline void FileDigestResult::clear_issamedigest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issamedigest_ = false;
}
inline bool FileDigestResult::issamedigest() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.FileDigestResult.isSameDigest)
  return _internal_issamedigest();
}
inline void FileDigestResult::set_issamedigest(bool value) {
  _internal_set_issamedigest(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.FileDigestResult.isSameDigest)
}
inline bool FileDigestResult::_internal_issamedigest() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.issamedigest_;
}
inline void FileDigestResult::_internal_set_issamedigest(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issamedigest_ = value;
}

// bool failed = 5;
inline void FileDigestResult::clear_failed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.failed_ = false;
}
inline bool FileDigestResult::failed() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.FileDigestResult.failed)
  return _internal_failed();
}
inline void FileDigestResult::set_failed(bool value) {
  _internal_set_failed(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.FileDigestResult.failed)
}
inline bool FileDigestResult::_internal_failed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.failed_;
}
inline void FileDigestResult::_internal_set_failed(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.failed_ = value;
}

// -------------------------------------------------------------------

// ClassDigestResult

// string strongClassname = 1;
inline void ClassDigestResult::clear_strongclassname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.strongclassname_.ClearToEmpty();
}
inline const std::string& ClassDigestResult::strongclassname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.ClassDigestResult.strongClassname)
  return _internal_strongclassname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ClassDigestResult::set_strongclassname(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.strongclassname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.ClassDigestResult.strongClassname)
}
inline std::string* ClassDigestResult::mutable_strongclassname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_strongclassname();
  // @@protoc_insertion_point(field_mutable:kapa.tarracsh.app.server.digest.ClassDigestResult.strongClassname)
  return _s;
}
inline const std::string& ClassDigestResult::_internal_strongclassname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.strongclassname_.Get();
}
inline void ClassDigestResult::_internal_set_strongclassname(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.strongclassname_.Set(value, GetArena());
}
inline std::string* ClassDigestResult::_internal_mutable_strongclassname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.strongclassname_.Mutable( GetArena());
}
inline std::string* ClassDigestResult::release_strongclassname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:kapa.tarracsh.app.server.digest.ClassDigestResult.strongClassname)
  return _impl_.strongclassname_.Release();
}
inline void ClassDigestResult::set_allocated_strongclassname(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.strongclassname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.strongclassname_.IsDefault()) {
    _impl_.strongclassname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:kapa.tarracsh.app.server.digest.ClassDigestResult.strongClassname)
}

// bool isNew = 2;
inline void ClassDigestResult::clear_isnew() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isnew_ = false;
}
inline bool ClassDigestResult::isnew() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.ClassDigestResult.isNew)
  return _internal_isnew();
}
inline void ClassDigestResult::set_isnew(bool value) {
  _internal_set_isnew(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.ClassDigestResult.isNew)
}
inline bool ClassDigestResult::_internal_isnew() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isnew_;
}
inline void ClassDigestResult::_internal_set_isnew(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isnew_ = value;
}

// bool isModified = 3;
inline void ClassDigestResult::clear_ismodified() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ismodified_ = false;
}
inline bool ClassDigestResult::ismodified() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.ClassDigestResult.isModified)
  return _internal_ismodified();
}
inline void ClassDigestResult::set_ismodified(bool value) {
  _internal_set_ismodified(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.ClassDigestResult.isModified)
}
inline bool ClassDigestResult::_internal_ismodified() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ismodified_;
}
inline void ClassDigestResult::_internal_set_ismodified(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ismodified_ = value;
}

// bool isSameDigest = 4;
inline void ClassDigestResult::clear_issamedigest() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issamedigest_ = false;
}
inline bool ClassDigestResult::issamedigest() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.ClassDigestResult.isSameDigest)
  return _internal_issamedigest();
}
inline void ClassDigestResult::set_issamedigest(bool value) {
  _internal_set_issamedigest(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.ClassDigestResult.isSameDigest)
}
inline bool ClassDigestResult::_internal_issamedigest() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.issamedigest_;
}
inline void ClassDigestResult::_internal_set_issamedigest(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.issamedigest_ = value;
}

// bool failed = 5;
inline void ClassDigestResult::clear_failed() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.failed_ = false;
}
inline bool ClassDigestResult::failed() const {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.ClassDigestResult.failed)
  return _internal_failed();
}
inline void ClassDigestResult::set_failed(bool value) {
  _internal_set_failed(value);
  // @@protoc_insertion_point(field_set:kapa.tarracsh.app.server.digest.ClassDigestResult.failed)
}
inline bool ClassDigestResult::_internal_failed() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.failed_;
}
inline void ClassDigestResult::_internal_set_failed(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.failed_ = value;
}

// -------------------------------------------------------------------

// DiffResponse

// repeated .kapa.tarracsh.app.server.digest.FileDigestResult files = 1;
inline int DiffResponse::_internal_files_size() const {
  return _internal_files().size();
}
inline int DiffResponse::files_size() const {
  return _internal_files_size();
}
inline void DiffResponse::clear_files() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.files_.Clear();
}
inline ::kapa::tarracsh::app::server::digest::FileDigestResult* DiffResponse::mutable_files(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:kapa.tarracsh.app.server.digest.DiffResponse.files)
  return _internal_mutable_files()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::FileDigestResult>* DiffResponse::mutable_files()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:kapa.tarracsh.app.server.digest.DiffResponse.files)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_files();
}
inline const ::kapa::tarracsh::app::server::digest::FileDigestResult& DiffResponse::files(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.DiffResponse.files)
  return _internal_files().Get(index);
}
inline ::kapa::tarracsh::app::server::digest::FileDigestResult* DiffResponse::add_files() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::kapa::tarracsh::app::server::digest::FileDigestResult* _add = _internal_mutable_files()->Add();
  // @@protoc_insertion_point(field_add:kapa.tarracsh.app.server.digest.DiffResponse.files)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::FileDigestResult>& DiffResponse::files() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:kapa.tarracsh.app.server.digest.DiffResponse.files)
  return _internal_files();
}
inline const ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::FileDigestResult>&
DiffResponse::_internal_files() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.files_;
}
inline ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::FileDigestResult>*
DiffResponse::_internal_mutable_files() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.files_;
}

// repeated .kapa.tarracsh.app.server.digest.ClassDigestResult classfiles = 2;
inline int DiffResponse::_internal_classfiles_size() const {
  return _internal_classfiles().size();
}
inline int DiffResponse::classfiles_size() const {
  return _internal_classfiles_size();
}
inline void DiffResponse::clear_classfiles() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.classfiles_.Clear();
}
inline ::kapa::tarracsh::app::server::digest::ClassDigestResult* DiffResponse::mutable_classfiles(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:kapa.tarracsh.app.server.digest.DiffResponse.classfiles)
  return _internal_mutable_classfiles()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::ClassDigestResult>* DiffResponse::mutable_classfiles()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:kapa.tarracsh.app.server.digest.DiffResponse.classfiles)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_classfiles();
}
inline const ::kapa::tarracsh::app::server::digest::ClassDigestResult& DiffResponse::classfiles(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:kapa.tarracsh.app.server.digest.DiffResponse.classfiles)
  return _internal_classfiles().Get(index);
}
inline ::kapa::tarracsh::app::server::digest::ClassDigestResult* DiffResponse::add_classfiles() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::kapa::tarracsh::app::server::digest::ClassDigestResult* _add = _internal_mutable_classfiles()->Add();
  // @@protoc_insertion_point(field_add:kapa.tarracsh.app.server.digest.DiffResponse.classfiles)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::ClassDigestResult>& DiffResponse::classfiles() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:kapa.tarracsh.app.server.digest.DiffResponse.classfiles)
  return _internal_classfiles();
}
inline const ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::ClassDigestResult>&
DiffResponse::_internal_classfiles() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.classfiles_;
}
inline ::google::protobuf::RepeatedPtrField<::kapa::tarracsh::app::server::digest::ClassDigestResult>*
DiffResponse::_internal_mutable_classfiles() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.classfiles_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace digest
}  // namespace server
}  // namespace app
}  // namespace tarracsh
}  // namespace kapa


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Server_2eproto_2epb_2eh
