// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server.proto

#include "Server.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace org {
namespace kapa {
namespace tarracsh {
namespace server {
namespace digest {
PROTOBUF_CONSTEXPR Empty::Empty(
    ::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
PROTOBUF_CONSTEXPR DigestRequest::DigestRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.input_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dryrun_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DigestRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DigestRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DigestRequestDefaultTypeInternal() {}
  union {
    DigestRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DigestRequestDefaultTypeInternal _DigestRequest_default_instance_;
PROTOBUF_CONSTEXPR FileDigestResult::FileDigestResult(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.filename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.isnew_)*/false
  , /*decltype(_impl_.ischanged_)*/false
  , /*decltype(_impl_.issamedigest_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FileDigestResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileDigestResultDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileDigestResultDefaultTypeInternal() {}
  union {
    FileDigestResult _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileDigestResultDefaultTypeInternal _FileDigestResult_default_instance_;
PROTOBUF_CONSTEXPR DigestResponse::DigestResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.jars_)*/{}
  , /*decltype(_impl_.classfiles_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DigestResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DigestResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DigestResponseDefaultTypeInternal() {}
  union {
    DigestResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DigestResponseDefaultTypeInternal _DigestResponse_default_instance_;
PROTOBUF_CONSTEXPR Point::Point(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.latitude_)*/0
  , /*decltype(_impl_.longitude_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PointDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PointDefaultTypeInternal() {}
  union {
    Point _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PointDefaultTypeInternal _Point_default_instance_;
PROTOBUF_CONSTEXPR Rectangle::Rectangle(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.lo_)*/nullptr
  , /*decltype(_impl_.hi_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RectangleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RectangleDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RectangleDefaultTypeInternal() {}
  union {
    Rectangle _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RectangleDefaultTypeInternal _Rectangle_default_instance_;
PROTOBUF_CONSTEXPR Feature::Feature(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.location_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FeatureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FeatureDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FeatureDefaultTypeInternal() {}
  union {
    Feature _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FeatureDefaultTypeInternal _Feature_default_instance_;
PROTOBUF_CONSTEXPR RouteNote::RouteNote(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.location_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RouteNoteDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RouteNoteDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RouteNoteDefaultTypeInternal() {}
  union {
    RouteNote _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RouteNoteDefaultTypeInternal _RouteNote_default_instance_;
PROTOBUF_CONSTEXPR RouteSummary::RouteSummary(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.point_count_)*/0
  , /*decltype(_impl_.feature_count_)*/0
  , /*decltype(_impl_.distance_)*/0
  , /*decltype(_impl_.elapsed_time_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RouteSummaryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RouteSummaryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RouteSummaryDefaultTypeInternal() {}
  union {
    RouteSummary _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RouteSummaryDefaultTypeInternal _RouteSummary_default_instance_;
}  // namespace digest
}  // namespace server
}  // namespace tarracsh
}  // namespace kapa
}  // namespace org
static ::_pb::Metadata file_level_metadata_Server_2eproto[9];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Server_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Server_2eproto = nullptr;

const uint32_t TableStruct_Server_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::DigestRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::DigestRequest, _impl_.input_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::DigestRequest, _impl_.dryrun_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::FileDigestResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::FileDigestResult, _impl_.filename_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::FileDigestResult, _impl_.isnew_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::FileDigestResult, _impl_.ischanged_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::FileDigestResult, _impl_.issamedigest_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::DigestResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::DigestResponse, _impl_.jars_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::DigestResponse, _impl_.classfiles_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Point, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Point, _impl_.latitude_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Point, _impl_.longitude_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Rectangle, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Rectangle, _impl_.lo_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Rectangle, _impl_.hi_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Feature, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Feature, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::Feature, _impl_.location_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::RouteNote, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::RouteNote, _impl_.location_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::RouteNote, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::RouteSummary, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::RouteSummary, _impl_.point_count_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::RouteSummary, _impl_.feature_count_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::RouteSummary, _impl_.distance_),
  PROTOBUF_FIELD_OFFSET(::org::kapa::tarracsh::server::digest::RouteSummary, _impl_.elapsed_time_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::Empty)},
  { 6, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::DigestRequest)},
  { 14, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::FileDigestResult)},
  { 24, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::DigestResponse)},
  { 32, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::Point)},
  { 40, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::Rectangle)},
  { 48, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::Feature)},
  { 56, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::RouteNote)},
  { 64, -1, -1, sizeof(::org::kapa::tarracsh::server::digest::RouteSummary)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::org::kapa::tarracsh::server::digest::_Empty_default_instance_._instance,
  &::org::kapa::tarracsh::server::digest::_DigestRequest_default_instance_._instance,
  &::org::kapa::tarracsh::server::digest::_FileDigestResult_default_instance_._instance,
  &::org::kapa::tarracsh::server::digest::_DigestResponse_default_instance_._instance,
  &::org::kapa::tarracsh::server::digest::_Point_default_instance_._instance,
  &::org::kapa::tarracsh::server::digest::_Rectangle_default_instance_._instance,
  &::org::kapa::tarracsh::server::digest::_Feature_default_instance_._instance,
  &::org::kapa::tarracsh::server::digest::_RouteNote_default_instance_._instance,
  &::org::kapa::tarracsh::server::digest::_RouteSummary_default_instance_._instance,
};

const char descriptor_table_protodef_Server_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Server.proto\022\037org.kapa.tarracsh.server"
  ".digest\"\007\n\005Empty\".\n\rDigestRequest\022\r\n\005inp"
  "ut\030\001 \001(\t\022\016\n\006dryRun\030\002 \001(\010\"\\\n\020FileDigestRe"
  "sult\022\020\n\010filename\030\001 \001(\t\022\r\n\005isNew\030\002 \001(\010\022\021\n"
  "\tisChanged\030\003 \001(\010\022\024\n\014isSameDigest\030\004 \001(\010\"\230"
  "\001\n\016DigestResponse\022\?\n\004jars\030\001 \003(\01321.org.ka"
  "pa.tarracsh.server.digest.FileDigestResu"
  "lt\022E\n\nclassfiles\030\002 \003(\01321.org.kapa.tarrac"
  "sh.server.digest.FileDigestResult\",\n\005Poi"
  "nt\022\020\n\010latitude\030\001 \001(\005\022\021\n\tlongitude\030\002 \001(\005\""
  "s\n\tRectangle\0222\n\002lo\030\001 \001(\0132&.org.kapa.tarr"
  "acsh.server.digest.Point\0222\n\002hi\030\002 \001(\0132&.o"
  "rg.kapa.tarracsh.server.digest.Point\"Q\n\007"
  "Feature\022\014\n\004name\030\001 \001(\t\0228\n\010location\030\002 \001(\0132"
  "&.org.kapa.tarracsh.server.digest.Point\""
  "V\n\tRouteNote\0228\n\010location\030\001 \001(\0132&.org.kap"
  "a.tarracsh.server.digest.Point\022\017\n\007messag"
  "e\030\002 \001(\t\"b\n\014RouteSummary\022\023\n\013point_count\030\001"
  " \001(\005\022\025\n\rfeature_count\030\002 \001(\005\022\020\n\010distance\030"
  "\003 \001(\005\022\024\n\014elapsed_time\030\004 \001(\0052\365\004\n\014PublicDi"
  "gest\022`\n\nGetFeature\022&.org.kapa.tarracsh.s"
  "erver.digest.Point\032(.org.kapa.tarracsh.s"
  "erver.digest.Feature\"\000\022h\n\014ListFeatures\022*"
  ".org.kapa.tarracsh.server.digest.Rectang"
  "le\032(.org.kapa.tarracsh.server.digest.Fea"
  "ture\"\0000\001\022h\n\013RecordRoute\022&.org.kapa.tarra"
  "csh.server.digest.Point\032-.org.kapa.tarra"
  "csh.server.digest.RouteSummary\"\000(\001\022i\n\tRo"
  "uteChat\022*.org.kapa.tarracsh.server.diges"
  "t.RouteNote\032*.org.kapa.tarracsh.server.d"
  "igest.RouteNote\"\000(\0010\001\022X\n\004Quit\022&.org.kapa"
  ".tarracsh.server.digest.Empty\032&.org.kapa"
  ".tarracsh.server.digest.Empty\"\000\022j\n\005Check"
  "\022..org.kapa.tarracsh.server.digest.Diges"
  "tRequest\032/.org.kapa.tarracsh.server.dige"
  "st.DigestResponse\"\000B6\n\033io.grpc.examples."
  "routeguideB\017RouteGuideProtoP\001\242\002\003RTGb\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_Server_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Server_2eproto = {
    false, false, 1483, descriptor_table_protodef_Server_2eproto,
    "Server.proto",
    &descriptor_table_Server_2eproto_once, nullptr, 0, 9,
    schemas, file_default_instances, TableStruct_Server_2eproto::offsets,
    file_level_metadata_Server_2eproto, file_level_enum_descriptors_Server_2eproto,
    file_level_service_descriptors_Server_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Server_2eproto_getter() {
  return &descriptor_table_Server_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Server_2eproto(&descriptor_table_Server_2eproto);
namespace org {
namespace kapa {
namespace tarracsh {
namespace server {
namespace digest {

// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.Empty)
}
Empty::Empty(const Empty& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Empty* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.Empty)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Empty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Empty::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[0]);
}

// ===================================================================

class DigestRequest::_Internal {
 public:
};

DigestRequest::DigestRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.DigestRequest)
}
DigestRequest::DigestRequest(const DigestRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DigestRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.input_){}
    , decltype(_impl_.dryrun_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.input_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.input_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_input().empty()) {
    _this->_impl_.input_.Set(from._internal_input(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.dryrun_ = from._impl_.dryrun_;
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.DigestRequest)
}

inline void DigestRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.input_){}
    , decltype(_impl_.dryrun_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.input_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.input_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DigestRequest::~DigestRequest() {
  // @@protoc_insertion_point(destructor:org.kapa.tarracsh.server.digest.DigestRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DigestRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.input_.Destroy();
}

void DigestRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DigestRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:org.kapa.tarracsh.server.digest.DigestRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.input_.ClearToEmpty();
  _impl_.dryrun_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DigestRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string input = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_input();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "org.kapa.tarracsh.server.digest.DigestRequest.input"));
        } else
          goto handle_unusual;
        continue;
      // bool dryRun = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.dryrun_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DigestRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.kapa.tarracsh.server.digest.DigestRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string input = 1;
  if (!this->_internal_input().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_input().data(), static_cast<int>(this->_internal_input().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "org.kapa.tarracsh.server.digest.DigestRequest.input");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_input(), target);
  }

  // bool dryRun = 2;
  if (this->_internal_dryrun() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_dryrun(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.kapa.tarracsh.server.digest.DigestRequest)
  return target;
}

size_t DigestRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.kapa.tarracsh.server.digest.DigestRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string input = 1;
  if (!this->_internal_input().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_input());
  }

  // bool dryRun = 2;
  if (this->_internal_dryrun() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DigestRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DigestRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DigestRequest::GetClassData() const { return &_class_data_; }


void DigestRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DigestRequest*>(&to_msg);
  auto& from = static_cast<const DigestRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.kapa.tarracsh.server.digest.DigestRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_input().empty()) {
    _this->_internal_set_input(from._internal_input());
  }
  if (from._internal_dryrun() != 0) {
    _this->_internal_set_dryrun(from._internal_dryrun());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DigestRequest::CopyFrom(const DigestRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.kapa.tarracsh.server.digest.DigestRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DigestRequest::IsInitialized() const {
  return true;
}

void DigestRequest::InternalSwap(DigestRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.input_, lhs_arena,
      &other->_impl_.input_, rhs_arena
  );
  swap(_impl_.dryrun_, other->_impl_.dryrun_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DigestRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[1]);
}

// ===================================================================

class FileDigestResult::_Internal {
 public:
};

FileDigestResult::FileDigestResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.FileDigestResult)
}
FileDigestResult::FileDigestResult(const FileDigestResult& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FileDigestResult* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.filename_){}
    , decltype(_impl_.isnew_){}
    , decltype(_impl_.ischanged_){}
    , decltype(_impl_.issamedigest_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filename().empty()) {
    _this->_impl_.filename_.Set(from._internal_filename(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.isnew_, &from._impl_.isnew_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.issamedigest_) -
    reinterpret_cast<char*>(&_impl_.isnew_)) + sizeof(_impl_.issamedigest_));
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.FileDigestResult)
}

inline void FileDigestResult::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.filename_){}
    , decltype(_impl_.isnew_){false}
    , decltype(_impl_.ischanged_){false}
    , decltype(_impl_.issamedigest_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FileDigestResult::~FileDigestResult() {
  // @@protoc_insertion_point(destructor:org.kapa.tarracsh.server.digest.FileDigestResult)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FileDigestResult::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.filename_.Destroy();
}

void FileDigestResult::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FileDigestResult::Clear() {
// @@protoc_insertion_point(message_clear_start:org.kapa.tarracsh.server.digest.FileDigestResult)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  ::memset(&_impl_.isnew_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.issamedigest_) -
      reinterpret_cast<char*>(&_impl_.isnew_)) + sizeof(_impl_.issamedigest_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FileDigestResult::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string filename = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_filename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "org.kapa.tarracsh.server.digest.FileDigestResult.filename"));
        } else
          goto handle_unusual;
        continue;
      // bool isNew = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.isnew_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool isChanged = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.ischanged_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool isSameDigest = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.issamedigest_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FileDigestResult::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.kapa.tarracsh.server.digest.FileDigestResult)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filename().data(), static_cast<int>(this->_internal_filename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "org.kapa.tarracsh.server.digest.FileDigestResult.filename");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_filename(), target);
  }

  // bool isNew = 2;
  if (this->_internal_isnew() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_isnew(), target);
  }

  // bool isChanged = 3;
  if (this->_internal_ischanged() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_ischanged(), target);
  }

  // bool isSameDigest = 4;
  if (this->_internal_issamedigest() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_issamedigest(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.kapa.tarracsh.server.digest.FileDigestResult)
  return target;
}

size_t FileDigestResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.kapa.tarracsh.server.digest.FileDigestResult)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filename());
  }

  // bool isNew = 2;
  if (this->_internal_isnew() != 0) {
    total_size += 1 + 1;
  }

  // bool isChanged = 3;
  if (this->_internal_ischanged() != 0) {
    total_size += 1 + 1;
  }

  // bool isSameDigest = 4;
  if (this->_internal_issamedigest() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FileDigestResult::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FileDigestResult::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FileDigestResult::GetClassData() const { return &_class_data_; }


void FileDigestResult::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FileDigestResult*>(&to_msg);
  auto& from = static_cast<const FileDigestResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.kapa.tarracsh.server.digest.FileDigestResult)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_isnew() != 0) {
    _this->_internal_set_isnew(from._internal_isnew());
  }
  if (from._internal_ischanged() != 0) {
    _this->_internal_set_ischanged(from._internal_ischanged());
  }
  if (from._internal_issamedigest() != 0) {
    _this->_internal_set_issamedigest(from._internal_issamedigest());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FileDigestResult::CopyFrom(const FileDigestResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.kapa.tarracsh.server.digest.FileDigestResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileDigestResult::IsInitialized() const {
  return true;
}

void FileDigestResult::InternalSwap(FileDigestResult* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filename_, lhs_arena,
      &other->_impl_.filename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.issamedigest_)
      + sizeof(FileDigestResult::_impl_.issamedigest_)
      - PROTOBUF_FIELD_OFFSET(FileDigestResult, _impl_.isnew_)>(
          reinterpret_cast<char*>(&_impl_.isnew_),
          reinterpret_cast<char*>(&other->_impl_.isnew_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FileDigestResult::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[2]);
}

// ===================================================================

class DigestResponse::_Internal {
 public:
};

DigestResponse::DigestResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.DigestResponse)
}
DigestResponse::DigestResponse(const DigestResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DigestResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.jars_){from._impl_.jars_}
    , decltype(_impl_.classfiles_){from._impl_.classfiles_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.DigestResponse)
}

inline void DigestResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.jars_){arena}
    , decltype(_impl_.classfiles_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DigestResponse::~DigestResponse() {
  // @@protoc_insertion_point(destructor:org.kapa.tarracsh.server.digest.DigestResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DigestResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.jars_.~RepeatedPtrField();
  _impl_.classfiles_.~RepeatedPtrField();
}

void DigestResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DigestResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:org.kapa.tarracsh.server.digest.DigestResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.jars_.Clear();
  _impl_.classfiles_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DigestResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .org.kapa.tarracsh.server.digest.FileDigestResult jars = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_jars(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .org.kapa.tarracsh.server.digest.FileDigestResult classfiles = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_classfiles(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DigestResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.kapa.tarracsh.server.digest.DigestResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .org.kapa.tarracsh.server.digest.FileDigestResult jars = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_jars_size()); i < n; i++) {
    const auto& repfield = this->_internal_jars(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .org.kapa.tarracsh.server.digest.FileDigestResult classfiles = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_classfiles_size()); i < n; i++) {
    const auto& repfield = this->_internal_classfiles(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.kapa.tarracsh.server.digest.DigestResponse)
  return target;
}

size_t DigestResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.kapa.tarracsh.server.digest.DigestResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .org.kapa.tarracsh.server.digest.FileDigestResult jars = 1;
  total_size += 1UL * this->_internal_jars_size();
  for (const auto& msg : this->_impl_.jars_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .org.kapa.tarracsh.server.digest.FileDigestResult classfiles = 2;
  total_size += 1UL * this->_internal_classfiles_size();
  for (const auto& msg : this->_impl_.classfiles_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DigestResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DigestResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DigestResponse::GetClassData() const { return &_class_data_; }


void DigestResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DigestResponse*>(&to_msg);
  auto& from = static_cast<const DigestResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.kapa.tarracsh.server.digest.DigestResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.jars_.MergeFrom(from._impl_.jars_);
  _this->_impl_.classfiles_.MergeFrom(from._impl_.classfiles_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DigestResponse::CopyFrom(const DigestResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.kapa.tarracsh.server.digest.DigestResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DigestResponse::IsInitialized() const {
  return true;
}

void DigestResponse::InternalSwap(DigestResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.jars_.InternalSwap(&other->_impl_.jars_);
  _impl_.classfiles_.InternalSwap(&other->_impl_.classfiles_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DigestResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[3]);
}

// ===================================================================

class Point::_Internal {
 public:
};

Point::Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.Point)
}
Point::Point(const Point& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Point* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.latitude_){}
    , decltype(_impl_.longitude_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.latitude_, &from._impl_.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.longitude_) -
    reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.longitude_));
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.Point)
}

inline void Point::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.latitude_){0}
    , decltype(_impl_.longitude_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Point::~Point() {
  // @@protoc_insertion_point(destructor:org.kapa.tarracsh.server.digest.Point)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Point::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Point::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Point::Clear() {
// @@protoc_insertion_point(message_clear_start:org.kapa.tarracsh.server.digest.Point)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.longitude_) -
      reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.longitude_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Point::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 latitude = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 longitude = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Point::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.kapa.tarracsh.server.digest.Point)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 latitude = 1;
  if (this->_internal_latitude() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_latitude(), target);
  }

  // int32 longitude = 2;
  if (this->_internal_longitude() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_longitude(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.kapa.tarracsh.server.digest.Point)
  return target;
}

size_t Point::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.kapa.tarracsh.server.digest.Point)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 latitude = 1;
  if (this->_internal_latitude() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_latitude());
  }

  // int32 longitude = 2;
  if (this->_internal_longitude() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_longitude());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Point::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Point::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Point::GetClassData() const { return &_class_data_; }


void Point::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Point*>(&to_msg);
  auto& from = static_cast<const Point&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.kapa.tarracsh.server.digest.Point)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_latitude() != 0) {
    _this->_internal_set_latitude(from._internal_latitude());
  }
  if (from._internal_longitude() != 0) {
    _this->_internal_set_longitude(from._internal_longitude());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Point::CopyFrom(const Point& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.kapa.tarracsh.server.digest.Point)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Point::IsInitialized() const {
  return true;
}

void Point::InternalSwap(Point* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Point, _impl_.longitude_)
      + sizeof(Point::_impl_.longitude_)
      - PROTOBUF_FIELD_OFFSET(Point, _impl_.latitude_)>(
          reinterpret_cast<char*>(&_impl_.latitude_),
          reinterpret_cast<char*>(&other->_impl_.latitude_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Point::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[4]);
}

// ===================================================================

class Rectangle::_Internal {
 public:
  static const ::org::kapa::tarracsh::server::digest::Point& lo(const Rectangle* msg);
  static const ::org::kapa::tarracsh::server::digest::Point& hi(const Rectangle* msg);
};

const ::org::kapa::tarracsh::server::digest::Point&
Rectangle::_Internal::lo(const Rectangle* msg) {
  return *msg->_impl_.lo_;
}
const ::org::kapa::tarracsh::server::digest::Point&
Rectangle::_Internal::hi(const Rectangle* msg) {
  return *msg->_impl_.hi_;
}
Rectangle::Rectangle(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.Rectangle)
}
Rectangle::Rectangle(const Rectangle& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Rectangle* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.lo_){nullptr}
    , decltype(_impl_.hi_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_lo()) {
    _this->_impl_.lo_ = new ::org::kapa::tarracsh::server::digest::Point(*from._impl_.lo_);
  }
  if (from._internal_has_hi()) {
    _this->_impl_.hi_ = new ::org::kapa::tarracsh::server::digest::Point(*from._impl_.hi_);
  }
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.Rectangle)
}

inline void Rectangle::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.lo_){nullptr}
    , decltype(_impl_.hi_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Rectangle::~Rectangle() {
  // @@protoc_insertion_point(destructor:org.kapa.tarracsh.server.digest.Rectangle)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Rectangle::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.lo_;
  if (this != internal_default_instance()) delete _impl_.hi_;
}

void Rectangle::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Rectangle::Clear() {
// @@protoc_insertion_point(message_clear_start:org.kapa.tarracsh.server.digest.Rectangle)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.lo_ != nullptr) {
    delete _impl_.lo_;
  }
  _impl_.lo_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.hi_ != nullptr) {
    delete _impl_.hi_;
  }
  _impl_.hi_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Rectangle::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .org.kapa.tarracsh.server.digest.Point lo = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_lo(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .org.kapa.tarracsh.server.digest.Point hi = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_hi(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Rectangle::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.kapa.tarracsh.server.digest.Rectangle)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .org.kapa.tarracsh.server.digest.Point lo = 1;
  if (this->_internal_has_lo()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::lo(this),
        _Internal::lo(this).GetCachedSize(), target, stream);
  }

  // .org.kapa.tarracsh.server.digest.Point hi = 2;
  if (this->_internal_has_hi()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::hi(this),
        _Internal::hi(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.kapa.tarracsh.server.digest.Rectangle)
  return target;
}

size_t Rectangle::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.kapa.tarracsh.server.digest.Rectangle)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .org.kapa.tarracsh.server.digest.Point lo = 1;
  if (this->_internal_has_lo()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.lo_);
  }

  // .org.kapa.tarracsh.server.digest.Point hi = 2;
  if (this->_internal_has_hi()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.hi_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Rectangle::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Rectangle::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Rectangle::GetClassData() const { return &_class_data_; }


void Rectangle::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Rectangle*>(&to_msg);
  auto& from = static_cast<const Rectangle&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.kapa.tarracsh.server.digest.Rectangle)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_lo()) {
    _this->_internal_mutable_lo()->::org::kapa::tarracsh::server::digest::Point::MergeFrom(
        from._internal_lo());
  }
  if (from._internal_has_hi()) {
    _this->_internal_mutable_hi()->::org::kapa::tarracsh::server::digest::Point::MergeFrom(
        from._internal_hi());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Rectangle::CopyFrom(const Rectangle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.kapa.tarracsh.server.digest.Rectangle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Rectangle::IsInitialized() const {
  return true;
}

void Rectangle::InternalSwap(Rectangle* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Rectangle, _impl_.hi_)
      + sizeof(Rectangle::_impl_.hi_)
      - PROTOBUF_FIELD_OFFSET(Rectangle, _impl_.lo_)>(
          reinterpret_cast<char*>(&_impl_.lo_),
          reinterpret_cast<char*>(&other->_impl_.lo_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Rectangle::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[5]);
}

// ===================================================================

class Feature::_Internal {
 public:
  static const ::org::kapa::tarracsh::server::digest::Point& location(const Feature* msg);
};

const ::org::kapa::tarracsh::server::digest::Point&
Feature::_Internal::location(const Feature* msg) {
  return *msg->_impl_.location_;
}
Feature::Feature(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.Feature)
}
Feature::Feature(const Feature& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Feature* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.location_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_location()) {
    _this->_impl_.location_ = new ::org::kapa::tarracsh::server::digest::Point(*from._impl_.location_);
  }
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.Feature)
}

inline void Feature::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.location_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Feature::~Feature() {
  // @@protoc_insertion_point(destructor:org.kapa.tarracsh.server.digest.Feature)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Feature::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  if (this != internal_default_instance()) delete _impl_.location_;
}

void Feature::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Feature::Clear() {
// @@protoc_insertion_point(message_clear_start:org.kapa.tarracsh.server.digest.Feature)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.location_ != nullptr) {
    delete _impl_.location_;
  }
  _impl_.location_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Feature::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "org.kapa.tarracsh.server.digest.Feature.name"));
        } else
          goto handle_unusual;
        continue;
      // .org.kapa.tarracsh.server.digest.Point location = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_location(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Feature::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.kapa.tarracsh.server.digest.Feature)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "org.kapa.tarracsh.server.digest.Feature.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // .org.kapa.tarracsh.server.digest.Point location = 2;
  if (this->_internal_has_location()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::location(this),
        _Internal::location(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.kapa.tarracsh.server.digest.Feature)
  return target;
}

size_t Feature::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.kapa.tarracsh.server.digest.Feature)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // .org.kapa.tarracsh.server.digest.Point location = 2;
  if (this->_internal_has_location()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.location_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Feature::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Feature::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Feature::GetClassData() const { return &_class_data_; }


void Feature::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Feature*>(&to_msg);
  auto& from = static_cast<const Feature&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.kapa.tarracsh.server.digest.Feature)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_has_location()) {
    _this->_internal_mutable_location()->::org::kapa::tarracsh::server::digest::Point::MergeFrom(
        from._internal_location());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Feature::CopyFrom(const Feature& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.kapa.tarracsh.server.digest.Feature)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Feature::IsInitialized() const {
  return true;
}

void Feature::InternalSwap(Feature* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  swap(_impl_.location_, other->_impl_.location_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Feature::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[6]);
}

// ===================================================================

class RouteNote::_Internal {
 public:
  static const ::org::kapa::tarracsh::server::digest::Point& location(const RouteNote* msg);
};

const ::org::kapa::tarracsh::server::digest::Point&
RouteNote::_Internal::location(const RouteNote* msg) {
  return *msg->_impl_.location_;
}
RouteNote::RouteNote(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.RouteNote)
}
RouteNote::RouteNote(const RouteNote& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RouteNote* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.location_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_location()) {
    _this->_impl_.location_ = new ::org::kapa::tarracsh::server::digest::Point(*from._impl_.location_);
  }
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.RouteNote)
}

inline void RouteNote::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.location_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RouteNote::~RouteNote() {
  // @@protoc_insertion_point(destructor:org.kapa.tarracsh.server.digest.RouteNote)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RouteNote::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
  if (this != internal_default_instance()) delete _impl_.location_;
}

void RouteNote::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RouteNote::Clear() {
// @@protoc_insertion_point(message_clear_start:org.kapa.tarracsh.server.digest.RouteNote)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.location_ != nullptr) {
    delete _impl_.location_;
  }
  _impl_.location_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RouteNote::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .org.kapa.tarracsh.server.digest.Point location = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_location(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "org.kapa.tarracsh.server.digest.RouteNote.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RouteNote::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.kapa.tarracsh.server.digest.RouteNote)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .org.kapa.tarracsh.server.digest.Point location = 1;
  if (this->_internal_has_location()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::location(this),
        _Internal::location(this).GetCachedSize(), target, stream);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "org.kapa.tarracsh.server.digest.RouteNote.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.kapa.tarracsh.server.digest.RouteNote)
  return target;
}

size_t RouteNote::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.kapa.tarracsh.server.digest.RouteNote)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // .org.kapa.tarracsh.server.digest.Point location = 1;
  if (this->_internal_has_location()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.location_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RouteNote::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RouteNote::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RouteNote::GetClassData() const { return &_class_data_; }


void RouteNote::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RouteNote*>(&to_msg);
  auto& from = static_cast<const RouteNote&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.kapa.tarracsh.server.digest.RouteNote)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_has_location()) {
    _this->_internal_mutable_location()->::org::kapa::tarracsh::server::digest::Point::MergeFrom(
        from._internal_location());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RouteNote::CopyFrom(const RouteNote& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.kapa.tarracsh.server.digest.RouteNote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RouteNote::IsInitialized() const {
  return true;
}

void RouteNote::InternalSwap(RouteNote* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.location_, other->_impl_.location_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RouteNote::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[7]);
}

// ===================================================================

class RouteSummary::_Internal {
 public:
};

RouteSummary::RouteSummary(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:org.kapa.tarracsh.server.digest.RouteSummary)
}
RouteSummary::RouteSummary(const RouteSummary& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RouteSummary* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.point_count_){}
    , decltype(_impl_.feature_count_){}
    , decltype(_impl_.distance_){}
    , decltype(_impl_.elapsed_time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.point_count_, &from._impl_.point_count_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.elapsed_time_) -
    reinterpret_cast<char*>(&_impl_.point_count_)) + sizeof(_impl_.elapsed_time_));
  // @@protoc_insertion_point(copy_constructor:org.kapa.tarracsh.server.digest.RouteSummary)
}

inline void RouteSummary::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.point_count_){0}
    , decltype(_impl_.feature_count_){0}
    , decltype(_impl_.distance_){0}
    , decltype(_impl_.elapsed_time_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

RouteSummary::~RouteSummary() {
  // @@protoc_insertion_point(destructor:org.kapa.tarracsh.server.digest.RouteSummary)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RouteSummary::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void RouteSummary::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RouteSummary::Clear() {
// @@protoc_insertion_point(message_clear_start:org.kapa.tarracsh.server.digest.RouteSummary)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.point_count_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.elapsed_time_) -
      reinterpret_cast<char*>(&_impl_.point_count_)) + sizeof(_impl_.elapsed_time_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RouteSummary::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 point_count = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.point_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 feature_count = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.feature_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 distance = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.distance_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 elapsed_time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.elapsed_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RouteSummary::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:org.kapa.tarracsh.server.digest.RouteSummary)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 point_count = 1;
  if (this->_internal_point_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_point_count(), target);
  }

  // int32 feature_count = 2;
  if (this->_internal_feature_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_feature_count(), target);
  }

  // int32 distance = 3;
  if (this->_internal_distance() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_distance(), target);
  }

  // int32 elapsed_time = 4;
  if (this->_internal_elapsed_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_elapsed_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.kapa.tarracsh.server.digest.RouteSummary)
  return target;
}

size_t RouteSummary::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:org.kapa.tarracsh.server.digest.RouteSummary)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 point_count = 1;
  if (this->_internal_point_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_point_count());
  }

  // int32 feature_count = 2;
  if (this->_internal_feature_count() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_feature_count());
  }

  // int32 distance = 3;
  if (this->_internal_distance() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_distance());
  }

  // int32 elapsed_time = 4;
  if (this->_internal_elapsed_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_elapsed_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RouteSummary::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RouteSummary::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RouteSummary::GetClassData() const { return &_class_data_; }


void RouteSummary::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RouteSummary*>(&to_msg);
  auto& from = static_cast<const RouteSummary&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:org.kapa.tarracsh.server.digest.RouteSummary)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_point_count() != 0) {
    _this->_internal_set_point_count(from._internal_point_count());
  }
  if (from._internal_feature_count() != 0) {
    _this->_internal_set_feature_count(from._internal_feature_count());
  }
  if (from._internal_distance() != 0) {
    _this->_internal_set_distance(from._internal_distance());
  }
  if (from._internal_elapsed_time() != 0) {
    _this->_internal_set_elapsed_time(from._internal_elapsed_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RouteSummary::CopyFrom(const RouteSummary& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:org.kapa.tarracsh.server.digest.RouteSummary)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RouteSummary::IsInitialized() const {
  return true;
}

void RouteSummary::InternalSwap(RouteSummary* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RouteSummary, _impl_.elapsed_time_)
      + sizeof(RouteSummary::_impl_.elapsed_time_)
      - PROTOBUF_FIELD_OFFSET(RouteSummary, _impl_.point_count_)>(
          reinterpret_cast<char*>(&_impl_.point_count_),
          reinterpret_cast<char*>(&other->_impl_.point_count_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RouteSummary::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Server_2eproto_getter, &descriptor_table_Server_2eproto_once,
      file_level_metadata_Server_2eproto[8]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace digest
}  // namespace server
}  // namespace tarracsh
}  // namespace kapa
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::Empty*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::Empty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::Empty >(arena);
}
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::DigestRequest*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::DigestRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::DigestRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::FileDigestResult*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::FileDigestResult >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::FileDigestResult >(arena);
}
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::DigestResponse*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::DigestResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::DigestResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::Point*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::Point >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::Point >(arena);
}
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::Rectangle*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::Rectangle >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::Rectangle >(arena);
}
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::Feature*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::Feature >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::Feature >(arena);
}
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::RouteNote*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::RouteNote >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::RouteNote >(arena);
}
template<> PROTOBUF_NOINLINE ::org::kapa::tarracsh::server::digest::RouteSummary*
Arena::CreateMaybeMessage< ::org::kapa::tarracsh::server::digest::RouteSummary >(Arena* arena) {
  return Arena::CreateMessageInternal< ::org::kapa::tarracsh::server::digest::RouteSummary >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
