graph [
  node [ id 0 label "_src/interfaces/cfdiff:cfdiff_" name "_src/interfaces/cfdiff:cfdiff_" ]
  node [ id 1 label "_at_bazel_toolstools/cpp:malloc_" name "_at_bazel_toolstools/cpp:malloc_" ]
  node [ id 2 label "_src/interfaces/cfdiff:cfdiff_lib_" name "_src/interfaces/cfdiff:cfdiff_lib_" ]
  node [ id 3 label "_at_bazel_toolstools/cpp:link_extra_lib_" name "_at_bazel_toolstools/cpp:link_extra_lib_" ]
  node [ id 4 label "_:vcpkg_runtime_libs_" name "_:vcpkg_runtime_libs_" ]
  node [ id 5 label "_at_bazel_toolstools/cpp:current_cc_toolchain_" name "_at_bazel_toolstools/cpp:current_cc_toolchain_" ]
  node [ id 6 label "_at_bazel_toolstools/def_parser:def_parser_" name "_at_bazel_toolstools/def_parser:def_parser_" ]
  node [ id 7 label "_at_bazel_toolstools/cpp:toolchain_type_" name "_at_bazel_toolstools/cpp:toolchain_type_" ]
  node [ id 8 label "_src/app:app_lib_" name "_src/app:app_lib_" ]
  node [ id 9 label "_src:tarracsh_" name "_src:tarracsh_" ]
  node [ id 10 label "_src/interfaces/tarracsh:tarracsh_" name "_src/interfaces/tarracsh:tarracsh_" ]
  node [ id 11 label "_src/interfaces/tarracsh:tarracsh_cli_lib_" name "_src/interfaces/tarracsh:tarracsh_cli_lib_" ]
  node [ id 12 label "_:vcpkg_headers_" name "_:vcpkg_headers_" ]
  node [ id 13 label "_src/domain:domain_lib_" name "_src/domain:domain_lib_" ]
  node [ id 14 label "_src/infrastructure:infrastructure_lib_" name "_src/infrastructure:infrastructure_lib_" ]
  node [ id 15 label "_at_vcpkg:runtime_libs_" name "_at_vcpkg:runtime_libs_" ]
  node [ id 16 label "_src/domain/db:db_lib_" name "_src/domain/db:db_lib_" ]
  node [ id 17 label "_src/infrastructure/db:db_lib_" name "_src/infrastructure/db:db_lib_" ]
  node [ id 18 label "_src/infrastructure/profiling:profiling_lib_" name "_src/infrastructure/profiling:profiling_lib_" ]
  node [ id 19 label "_src/infrastructure/log:log_lib_" name "_src/infrastructure/log:log_lib_" ]
  node [ id 20 label "_src/infrastructure/string:string_lib_" name "_src/infrastructure/string:string_lib_" ]
  node [ id 21 label "_src/infrastructure/app:cli_lib_" name "_src/infrastructure/app:cli_lib_" ]
  node [ id 22 label "_src/infrastructure/filesystem:filesystem_lib_" name "_src/infrastructure/filesystem:filesystem_lib_" ]
  node [ id 23 label "_at_vcpkg:headers_" name "_at_vcpkg:headers_" ]
  node [ id 24 label "_atat_platformsos:windows_" name "_atat_platformsos:windows_" ]
  node [ id 25 label "_at_bazel_toolsthird_party/def_parser:def_parser_" name "_at_bazel_toolsthird_party/def_parser:def_parser_" ]
  node [ id 26 label "_at_bazel_toolsthird_party/def_parser:def_parser_lib_" name "_at_bazel_toolsthird_party/def_parser:def_parser_lib_" ]
  node [ id 27 label "_atat_platformsos:os_" name "_atat_platformsos:os_" ]
  node [ id 28 label "_at_bazel_toolstools/cpp:link_extra_libs_" name "_at_bazel_toolstools/cpp:link_extra_libs_" ]
  node [ id 29 label "_at_bazel_toolstools/cpp:empty_lib_" name "_at_bazel_toolstools/cpp:empty_lib_" ]
  node [ id 30 label "_atat_rules_cc_cc:current_cc_toolchain_" name "_atat_rules_cc_cc:current_cc_toolchain_" ]
  edge [ source 0 target 1 ]
  edge [ source 0 target 2 ]
  edge [ source 0 target 3 ]
  edge [ source 0 target 4 ]
  edge [ source 0 target 5 ]
  edge [ source 0 target 6 ]
  edge [ source 0 target 7 ]
  edge [ source 1 target 5 ]
  edge [ source 1 target 7 ]
  edge [ source 2 target 5 ]
  edge [ source 2 target 6 ]
  edge [ source 2 target 7 ]
  edge [ source 2 target 8 ]
  edge [ source 3 target 5 ]
  edge [ source 3 target 7 ]
  edge [ source 3 target 28 ]
  edge [ source 4 target 15 ]
  edge [ source 5 target 30 ]
  edge [ source 6 target 24 ]
  edge [ source 6 target 25 ]
  edge [ source 8 target 5 ]
  edge [ source 8 target 6 ]
  edge [ source 8 target 7 ]
  edge [ source 8 target 12 ]
  edge [ source 8 target 13 ]
  edge [ source 8 target 14 ]
  edge [ source 9 target 10 ]
  edge [ source 10 target 1 ]
  edge [ source 10 target 3 ]
  edge [ source 10 target 4 ]
  edge [ source 10 target 5 ]
  edge [ source 10 target 6 ]
  edge [ source 10 target 7 ]
  edge [ source 10 target 11 ]
  edge [ source 11 target 5 ]
  edge [ source 11 target 6 ]
  edge [ source 11 target 7 ]
  edge [ source 11 target 8 ]
  edge [ source 12 target 23 ]
  edge [ source 13 target 5 ]
  edge [ source 13 target 6 ]
  edge [ source 13 target 7 ]
  edge [ source 13 target 12 ]
  edge [ source 13 target 14 ]
  edge [ source 13 target 16 ]
  edge [ source 14 target 5 ]
  edge [ source 14 target 6 ]
  edge [ source 14 target 7 ]
  edge [ source 14 target 12 ]
  edge [ source 14 target 17 ]
  edge [ source 14 target 18 ]
  edge [ source 14 target 19 ]
  edge [ source 14 target 20 ]
  edge [ source 14 target 21 ]
  edge [ source 14 target 22 ]
  edge [ source 15 target 5 ]
  edge [ source 15 target 6 ]
  edge [ source 15 target 7 ]
  edge [ source 15 target 23 ]
  edge [ source 16 target 5 ]
  edge [ source 16 target 6 ]
  edge [ source 16 target 7 ]
  edge [ source 16 target 12 ]
  edge [ source 16 target 17 ]
  edge [ source 16 target 18 ]
  edge [ source 16 target 19 ]
  edge [ source 16 target 20 ]
  edge [ source 17 target 5 ]
  edge [ source 17 target 6 ]
  edge [ source 17 target 7 ]
  edge [ source 17 target 12 ]
  edge [ source 17 target 18 ]
  edge [ source 17 target 19 ]
  edge [ source 17 target 20 ]
  edge [ source 18 target 5 ]
  edge [ source 18 target 6 ]
  edge [ source 18 target 7 ]
  edge [ source 18 target 12 ]
  edge [ source 18 target 22 ]
  edge [ source 19 target 5 ]
  edge [ source 19 target 6 ]
  edge [ source 19 target 7 ]
  edge [ source 20 target 5 ]
  edge [ source 20 target 6 ]
  edge [ source 20 target 7 ]
  edge [ source 20 target 12 ]
  edge [ source 21 target 5 ]
  edge [ source 21 target 6 ]
  edge [ source 21 target 7 ]
  edge [ source 21 target 12 ]
  edge [ source 21 target 19 ]
  edge [ source 22 target 5 ]
  edge [ source 22 target 6 ]
  edge [ source 22 target 7 ]
  edge [ source 23 target 5 ]
  edge [ source 23 target 6 ]
  edge [ source 23 target 7 ]
  edge [ source 24 target 27 ]
  edge [ source 25 target 1 ]
  edge [ source 25 target 3 ]
  edge [ source 25 target 5 ]
  edge [ source 25 target 7 ]
  edge [ source 25 target 26 ]
  edge [ source 26 target 5 ]
  edge [ source 26 target 7 ]
  edge [ source 28 target 29 ]
  edge [ source 29 target 5 ]
  edge [ source 29 target 7 ]
  edge [ source 30 target 7 ]
]
