graph [
  node [ id 0 label "_src/interfaces/cfdiff:cfdiff_" name "_src/interfaces/cfdiff:cfdiff_" ]
  node [ id 1 label "_at_bazel_toolstools/cpp:current_cc_toolchain_" name "_at_bazel_toolstools/cpp:current_cc_toolchain_" ]
  node [ id 2 label "_src/interfaces/cfdiff:cfdiff_lib_" name "_src/interfaces/cfdiff:cfdiff_lib_" ]
  node [ id 3 label "_at_bazel_toolstools/cpp:malloc_" name "_at_bazel_toolstools/cpp:malloc_" ]
  node [ id 4 label "_:vcpkg_runtime_libs_" name "_:vcpkg_runtime_libs_" ]
  node [ id 5 label "_at_bazel_toolstools/cpp:link_extra_lib_" name "_at_bazel_toolstools/cpp:link_extra_lib_" ]
  node [ id 6 label "_at_bazel_toolstools/def_parser:def_parser_" name "_at_bazel_toolstools/def_parser:def_parser_" ]
  node [ id 7 label "_at_bazel_toolstools/cpp:toolchain_type_" name "_at_bazel_toolstools/cpp:toolchain_type_" ]
  node [ id 8 label "_src:tarracsh_" name "_src:tarracsh_" ]
  node [ id 9 label "_src/interfaces/tarracsh:tarracsh_" name "_src/interfaces/tarracsh:tarracsh_" ]
  node [ id 10 label "_src/interfaces/tarracsh:tarracsh_cli_lib_" name "_src/interfaces/tarracsh:tarracsh_cli_lib_" ]
  node [ id 11 label "_src/app/server:app_server_lib_" name "_src/app/server:app_server_lib_" ]
  node [ id 12 label "_src/app/commands:app_commands_lib_" name "_src/app/commands:app_commands_lib_" ]
  node [ id 13 label "_src/app:app_lib_" name "_src/app:app_lib_" ]
  node [ id 14 label "_src/app/commands:app_commands_lib_core_" name "_src/app/commands:app_commands_lib_core_" ]
  node [ id 15 label "_src/app/commands/callgraph:callgraph_lib_" name "_src/app/commands/callgraph:callgraph_lib_" ]
  node [ id 16 label "_src/app/commands/digest:digest_lib_" name "_src/app/commands/digest:digest_lib_" ]
  node [ id 17 label "_src/app/server/digest:digest_lib_" name "_src/app/server/digest:digest_lib_" ]
  node [ id 18 label "_src/domain/jar:jar_lib_" name "_src/domain/jar:jar_lib_" ]
  node [ id 19 label "_src/domain:domain_lib_" name "_src/domain:domain_lib_" ]
  node [ id 20 label "_:vcpkg_headers_" name "_:vcpkg_headers_" ]
  node [ id 21 label "_src/infrastructure:infrastructure_lib_" name "_src/infrastructure:infrastructure_lib_" ]
  node [ id 22 label "_at_vcpkg:runtime_libs_" name "_at_vcpkg:runtime_libs_" ]
  node [ id 23 label "_at_vcpkg:headers_" name "_at_vcpkg:headers_" ]
  node [ id 24 label "_src/app/server:app_server_lib_core_" name "_src/app/server:app_server_lib_core_" ]
  node [ id 25 label "_src/app/server/digest/proto:proto_lib_" name "_src/app/server/digest/proto:proto_lib_" ]
  node [ id 26 label "_src/app/classfile:app_classfile_lib_" name "_src/app/classfile:app_classfile_lib_" ]
  node [ id 27 label "_src/app:app_context_lib_" name "_src/app:app_context_lib_" ]
  node [ id 28 label "_src/app/classfile/constantpool:constantpool_lib_" name "_src/app/classfile/constantpool:constantpool_lib_" ]
  node [ id 29 label "_src/domain:utils_lib_" name "_src/domain:utils_lib_" ]
  node [ id 30 label "_src/domain:options_lib_" name "_src/domain:options_lib_" ]
  node [ id 31 label "_src/domain/stats:stats_lib_" name "_src/domain/stats:stats_lib_" ]
  node [ id 32 label "_src/domain/graph:graph_lib_" name "_src/domain/graph:graph_lib_" ]
  node [ id 33 label "_src/domain/classfile:classfile_lib_" name "_src/domain/classfile:classfile_lib_" ]
  node [ id 34 label "_src/domain/db:db_lib_" name "_src/domain/db:db_lib_" ]
  node [ id 35 label "_src/domain/digest:digest_lib_" name "_src/domain/digest:digest_lib_" ]
  node [ id 36 label "_src/domain/db:callgraph_lib_" name "_src/domain/db:callgraph_lib_" ]
  node [ id 37 label "_src/domain/jar:jar_core_" name "_src/domain/jar:jar_core_" ]
  node [ id 38 label "_src/domain/jar/tasks:tasks_lib_" name "_src/domain/jar/tasks:tasks_lib_" ]
  node [ id 39 label "_src/domain/jar/tasks:task_base_" name "_src/domain/jar/tasks:task_base_" ]
  node [ id 40 label "_src/infrastructure/log:log_lib_" name "_src/infrastructure/log:log_lib_" ]
  node [ id 41 label "_src/infrastructure/filesystem:filesystem_lib_" name "_src/infrastructure/filesystem:filesystem_lib_" ]
  node [ id 42 label "_src/infrastructure/db:db_lib_" name "_src/infrastructure/db:db_lib_" ]
  node [ id 43 label "_src/domain/jar:jar_api_" name "_src/domain/jar:jar_api_" ]
  node [ id 44 label "_src/domain/db/table:table_lib_" name "_src/domain/db/table:table_lib_" ]
  node [ id 45 label "_src/infrastructure/profiling:profiling_lib_" name "_src/infrastructure/profiling:profiling_lib_" ]
  node [ id 46 label "_src/infrastructure/string:string_lib_" name "_src/infrastructure/string:string_lib_" ]
  node [ id 47 label "_src/app/classfile/constantpool/printer/nav:nav_lib_" name "_src/app/classfile/constantpool/printer/nav:nav_lib_" ]
  node [ id 48 label "_src/app/classfile/constantpool/printer:printer_lib_" name "_src/app/classfile/constantpool/printer:printer_lib_" ]
  node [ id 49 label "_src/domain/classfile/reader:reader_lib_" name "_src/domain/classfile/reader:reader_lib_" ]
  node [ id 50 label "_src/domain/classfile/signature:signature_lib_" name "_src/domain/classfile/signature:signature_lib_" ]
  node [ id 51 label "_src/domain/classfile/types:types_lib_" name "_src/domain/classfile/types:types_lib_" ]
  node [ id 52 label "_src/domain/classfile/constantpool:constantpool_lib_" name "_src/domain/classfile/constantpool:constantpool_lib_" ]
  node [ id 53 label "_src/domain/classfile:descriptor_parsers_" name "_src/domain/classfile:descriptor_parsers_" ]
  node [ id 54 label "_src/domain/classfile/signature:signature_scanner_" name "_src/domain/classfile/signature:signature_scanner_" ]
  node [ id 55 label "_src/domain/classfile/signature/parser:signature_parser_core_" name "_src/domain/classfile/signature/parser:signature_parser_core_" ]
  node [ id 56 label "_src/domain/db/columns:columns_hdrs_" name "_src/domain/db/columns:columns_hdrs_" ]
  node [ id 57 label "_src/infrastructure/app:cli_lib_" name "_src/infrastructure/app:cli_lib_" ]
  node [ id 58 label "_src/domain/classfile:classfile_constants_" name "_src/domain/classfile:classfile_constants_" ]
  node [ id 59 label "_atat_platformsos:windows_" name "_atat_platformsos:windows_" ]
  node [ id 60 label "_at_bazel_toolsthird_party/def_parser:def_parser_" name "_at_bazel_toolsthird_party/def_parser:def_parser_" ]
  node [ id 61 label "_at_bazel_toolsthird_party/def_parser:def_parser_lib_" name "_at_bazel_toolsthird_party/def_parser:def_parser_lib_" ]
  node [ id 62 label "_at_bazel_toolstools/cpp:link_extra_libs_" name "_at_bazel_toolstools/cpp:link_extra_libs_" ]
  node [ id 63 label "_at_bazel_toolstools/cpp:empty_lib_" name "_at_bazel_toolstools/cpp:empty_lib_" ]
  node [ id 64 label "_atat_platformsos:os_" name "_atat_platformsos:os_" ]
  node [ id 65 label "_atat_rules_cc_cc:current_cc_toolchain_" name "_atat_rules_cc_cc:current_cc_toolchain_" ]
  edge [ source 0 target 1 ]
  edge [ source 0 target 2 ]
  edge [ source 0 target 3 ]
  edge [ source 0 target 4 ]
  edge [ source 0 target 5 ]
  edge [ source 0 target 6 ]
  edge [ source 0 target 7 ]
  edge [ source 1 target 65 ]
  edge [ source 2 target 1 ]
  edge [ source 2 target 6 ]
  edge [ source 2 target 7 ]
  edge [ source 2 target 13 ]
  edge [ source 3 target 1 ]
  edge [ source 3 target 7 ]
  edge [ source 4 target 22 ]
  edge [ source 5 target 1 ]
  edge [ source 5 target 7 ]
  edge [ source 5 target 62 ]
  edge [ source 6 target 59 ]
  edge [ source 6 target 60 ]
  edge [ source 8 target 9 ]
  edge [ source 9 target 1 ]
  edge [ source 9 target 3 ]
  edge [ source 9 target 4 ]
  edge [ source 9 target 5 ]
  edge [ source 9 target 6 ]
  edge [ source 9 target 7 ]
  edge [ source 9 target 10 ]
  edge [ source 10 target 1 ]
  edge [ source 10 target 6 ]
  edge [ source 10 target 7 ]
  edge [ source 10 target 11 ]
  edge [ source 10 target 12 ]
  edge [ source 10 target 13 ]
  edge [ source 11 target 1 ]
  edge [ source 11 target 6 ]
  edge [ source 11 target 7 ]
  edge [ source 11 target 17 ]
  edge [ source 11 target 24 ]
  edge [ source 12 target 1 ]
  edge [ source 12 target 6 ]
  edge [ source 12 target 7 ]
  edge [ source 12 target 14 ]
  edge [ source 12 target 15 ]
  edge [ source 12 target 16 ]
  edge [ source 13 target 1 ]
  edge [ source 13 target 6 ]
  edge [ source 13 target 7 ]
  edge [ source 13 target 19 ]
  edge [ source 13 target 20 ]
  edge [ source 13 target 21 ]
  edge [ source 13 target 26 ]
  edge [ source 13 target 27 ]
  edge [ source 14 target 1 ]
  edge [ source 14 target 6 ]
  edge [ source 14 target 7 ]
  edge [ source 14 target 11 ]
  edge [ source 14 target 13 ]
  edge [ source 14 target 19 ]
  edge [ source 14 target 20 ]
  edge [ source 14 target 21 ]
  edge [ source 15 target 1 ]
  edge [ source 15 target 6 ]
  edge [ source 15 target 7 ]
  edge [ source 15 target 13 ]
  edge [ source 15 target 14 ]
  edge [ source 15 target 18 ]
  edge [ source 15 target 19 ]
  edge [ source 15 target 20 ]
  edge [ source 15 target 21 ]
  edge [ source 16 target 1 ]
  edge [ source 16 target 6 ]
  edge [ source 16 target 7 ]
  edge [ source 16 target 13 ]
  edge [ source 16 target 14 ]
  edge [ source 16 target 17 ]
  edge [ source 16 target 18 ]
  edge [ source 16 target 19 ]
  edge [ source 16 target 20 ]
  edge [ source 16 target 21 ]
  edge [ source 17 target 1 ]
  edge [ source 17 target 6 ]
  edge [ source 17 target 7 ]
  edge [ source 17 target 13 ]
  edge [ source 17 target 19 ]
  edge [ source 17 target 20 ]
  edge [ source 17 target 21 ]
  edge [ source 17 target 24 ]
  edge [ source 17 target 25 ]
  edge [ source 18 target 1 ]
  edge [ source 18 target 6 ]
  edge [ source 18 target 7 ]
  edge [ source 18 target 37 ]
  edge [ source 18 target 38 ]
  edge [ source 19 target 1 ]
  edge [ source 19 target 6 ]
  edge [ source 19 target 7 ]
  edge [ source 19 target 18 ]
  edge [ source 19 target 20 ]
  edge [ source 19 target 21 ]
  edge [ source 19 target 29 ]
  edge [ source 19 target 30 ]
  edge [ source 19 target 31 ]
  edge [ source 19 target 32 ]
  edge [ source 19 target 33 ]
  edge [ source 19 target 34 ]
  edge [ source 19 target 35 ]
  edge [ source 19 target 36 ]
  edge [ source 20 target 23 ]
  edge [ source 21 target 1 ]
  edge [ source 21 target 6 ]
  edge [ source 21 target 7 ]
  edge [ source 21 target 20 ]
  edge [ source 21 target 40 ]
  edge [ source 21 target 41 ]
  edge [ source 21 target 42 ]
  edge [ source 21 target 45 ]
  edge [ source 21 target 46 ]
  edge [ source 21 target 57 ]
  edge [ source 22 target 1 ]
  edge [ source 22 target 6 ]
  edge [ source 22 target 7 ]
  edge [ source 22 target 23 ]
  edge [ source 23 target 1 ]
  edge [ source 23 target 6 ]
  edge [ source 23 target 7 ]
  edge [ source 24 target 1 ]
  edge [ source 24 target 6 ]
  edge [ source 24 target 7 ]
  edge [ source 24 target 13 ]
  edge [ source 24 target 19 ]
  edge [ source 24 target 20 ]
  edge [ source 24 target 21 ]
  edge [ source 24 target 25 ]
  edge [ source 25 target 1 ]
  edge [ source 25 target 6 ]
  edge [ source 25 target 7 ]
  edge [ source 25 target 20 ]
  edge [ source 26 target 1 ]
  edge [ source 26 target 6 ]
  edge [ source 26 target 7 ]
  edge [ source 26 target 19 ]
  edge [ source 26 target 20 ]
  edge [ source 26 target 21 ]
  edge [ source 26 target 28 ]
  edge [ source 27 target 1 ]
  edge [ source 27 target 6 ]
  edge [ source 27 target 7 ]
  edge [ source 27 target 21 ]
  edge [ source 27 target 30 ]
  edge [ source 27 target 31 ]
  edge [ source 28 target 1 ]
  edge [ source 28 target 6 ]
  edge [ source 28 target 7 ]
  edge [ source 28 target 47 ]
  edge [ source 28 target 48 ]
  edge [ source 29 target 1 ]
  edge [ source 29 target 6 ]
  edge [ source 29 target 7 ]
  edge [ source 29 target 42 ]
  edge [ source 29 target 46 ]
  edge [ source 30 target 1 ]
  edge [ source 30 target 6 ]
  edge [ source 30 target 7 ]
  edge [ source 30 target 20 ]
  edge [ source 30 target 41 ]
  edge [ source 31 target 1 ]
  edge [ source 31 target 6 ]
  edge [ source 31 target 7 ]
  edge [ source 31 target 20 ]
  edge [ source 31 target 29 ]
  edge [ source 31 target 30 ]
  edge [ source 31 target 35 ]
  edge [ source 31 target 40 ]
  edge [ source 31 target 41 ]
  edge [ source 32 target 1 ]
  edge [ source 32 target 6 ]
  edge [ source 32 target 7 ]
  edge [ source 32 target 20 ]
  edge [ source 32 target 29 ]
  edge [ source 32 target 33 ]
  edge [ source 32 target 34 ]
  edge [ source 32 target 36 ]
  edge [ source 33 target 1 ]
  edge [ source 33 target 6 ]
  edge [ source 33 target 7 ]
  edge [ source 33 target 20 ]
  edge [ source 33 target 29 ]
  edge [ source 33 target 40 ]
  edge [ source 33 target 41 ]
  edge [ source 33 target 46 ]
  edge [ source 33 target 49 ]
  edge [ source 33 target 50 ]
  edge [ source 33 target 51 ]
  edge [ source 33 target 52 ]
  edge [ source 33 target 53 ]
  edge [ source 34 target 1 ]
  edge [ source 34 target 6 ]
  edge [ source 34 target 7 ]
  edge [ source 34 target 20 ]
  edge [ source 34 target 29 ]
  edge [ source 34 target 40 ]
  edge [ source 34 target 42 ]
  edge [ source 34 target 44 ]
  edge [ source 34 target 45 ]
  edge [ source 34 target 46 ]
  edge [ source 35 target 1 ]
  edge [ source 35 target 6 ]
  edge [ source 35 target 7 ]
  edge [ source 35 target 20 ]
  edge [ source 35 target 29 ]
  edge [ source 35 target 33 ]
  edge [ source 35 target 34 ]
  edge [ source 35 target 46 ]
  edge [ source 36 target 1 ]
  edge [ source 36 target 6 ]
  edge [ source 36 target 7 ]
  edge [ source 36 target 20 ]
  edge [ source 36 target 29 ]
  edge [ source 36 target 40 ]
  edge [ source 36 target 42 ]
  edge [ source 36 target 44 ]
  edge [ source 36 target 45 ]
  edge [ source 36 target 46 ]
  edge [ source 37 target 1 ]
  edge [ source 37 target 6 ]
  edge [ source 37 target 7 ]
  edge [ source 37 target 20 ]
  edge [ source 37 target 29 ]
  edge [ source 37 target 30 ]
  edge [ source 37 target 31 ]
  edge [ source 37 target 33 ]
  edge [ source 37 target 34 ]
  edge [ source 37 target 39 ]
  edge [ source 37 target 40 ]
  edge [ source 37 target 41 ]
  edge [ source 37 target 43 ]
  edge [ source 38 target 1 ]
  edge [ source 38 target 6 ]
  edge [ source 38 target 7 ]
  edge [ source 38 target 20 ]
  edge [ source 38 target 29 ]
  edge [ source 38 target 30 ]
  edge [ source 38 target 31 ]
  edge [ source 38 target 32 ]
  edge [ source 38 target 33 ]
  edge [ source 38 target 34 ]
  edge [ source 38 target 35 ]
  edge [ source 38 target 36 ]
  edge [ source 38 target 39 ]
  edge [ source 38 target 40 ]
  edge [ source 38 target 41 ]
  edge [ source 38 target 42 ]
  edge [ source 38 target 43 ]
  edge [ source 39 target 1 ]
  edge [ source 39 target 6 ]
  edge [ source 39 target 7 ]
  edge [ source 39 target 20 ]
  edge [ source 39 target 29 ]
  edge [ source 39 target 30 ]
  edge [ source 39 target 31 ]
  edge [ source 39 target 34 ]
  edge [ source 39 target 42 ]
  edge [ source 39 target 43 ]
  edge [ source 40 target 1 ]
  edge [ source 40 target 6 ]
  edge [ source 40 target 7 ]
  edge [ source 41 target 1 ]
  edge [ source 41 target 6 ]
  edge [ source 41 target 7 ]
  edge [ source 42 target 1 ]
  edge [ source 42 target 6 ]
  edge [ source 42 target 7 ]
  edge [ source 42 target 20 ]
  edge [ source 42 target 40 ]
  edge [ source 42 target 45 ]
  edge [ source 42 target 46 ]
  edge [ source 43 target 1 ]
  edge [ source 43 target 6 ]
  edge [ source 43 target 7 ]
  edge [ source 43 target 20 ]
  edge [ source 43 target 29 ]
  edge [ source 44 target 1 ]
  edge [ source 44 target 6 ]
  edge [ source 44 target 7 ]
  edge [ source 44 target 20 ]
  edge [ source 44 target 29 ]
  edge [ source 44 target 42 ]
  edge [ source 44 target 46 ]
  edge [ source 44 target 56 ]
  edge [ source 45 target 1 ]
  edge [ source 45 target 6 ]
  edge [ source 45 target 7 ]
  edge [ source 45 target 20 ]
  edge [ source 45 target 41 ]
  edge [ source 46 target 1 ]
  edge [ source 46 target 6 ]
  edge [ source 46 target 7 ]
  edge [ source 46 target 20 ]
  edge [ source 47 target 1 ]
  edge [ source 47 target 6 ]
  edge [ source 47 target 7 ]
  edge [ source 47 target 20 ]
  edge [ source 47 target 30 ]
  edge [ source 47 target 33 ]
  edge [ source 47 target 41 ]
  edge [ source 47 target 46 ]
  edge [ source 47 target 48 ]
  edge [ source 48 target 1 ]
  edge [ source 48 target 6 ]
  edge [ source 48 target 7 ]
  edge [ source 48 target 20 ]
  edge [ source 48 target 27 ]
  edge [ source 48 target 33 ]
  edge [ source 49 target 1 ]
  edge [ source 49 target 6 ]
  edge [ source 49 target 7 ]
  edge [ source 49 target 51 ]
  edge [ source 50 target 1 ]
  edge [ source 50 target 6 ]
  edge [ source 50 target 7 ]
  edge [ source 50 target 20 ]
  edge [ source 50 target 49 ]
  edge [ source 50 target 51 ]
  edge [ source 50 target 52 ]
  edge [ source 50 target 54 ]
  edge [ source 50 target 55 ]
  edge [ source 51 target 1 ]
  edge [ source 51 target 6 ]
  edge [ source 51 target 7 ]
  edge [ source 51 target 58 ]
  edge [ source 52 target 1 ]
  edge [ source 52 target 6 ]
  edge [ source 52 target 7 ]
  edge [ source 52 target 46 ]
  edge [ source 52 target 51 ]
  edge [ source 52 target 53 ]
  edge [ source 53 target 1 ]
  edge [ source 53 target 6 ]
  edge [ source 53 target 7 ]
  edge [ source 53 target 51 ]
  edge [ source 53 target 54 ]
  edge [ source 54 target 1 ]
  edge [ source 54 target 6 ]
  edge [ source 54 target 7 ]
  edge [ source 55 target 1 ]
  edge [ source 55 target 6 ]
  edge [ source 55 target 7 ]
  edge [ source 55 target 20 ]
  edge [ source 55 target 51 ]
  edge [ source 57 target 1 ]
  edge [ source 57 target 6 ]
  edge [ source 57 target 7 ]
  edge [ source 57 target 20 ]
  edge [ source 57 target 40 ]
  edge [ source 58 target 1 ]
  edge [ source 58 target 6 ]
  edge [ source 58 target 7 ]
  edge [ source 59 target 64 ]
  edge [ source 60 target 1 ]
  edge [ source 60 target 3 ]
  edge [ source 60 target 5 ]
  edge [ source 60 target 7 ]
  edge [ source 60 target 61 ]
  edge [ source 61 target 1 ]
  edge [ source 61 target 7 ]
  edge [ source 62 target 63 ]
  edge [ source 63 target 1 ]
  edge [ source 63 target 7 ]
  edge [ source 65 target 7 ]
]
