graph [
  node [ id 0 label "_src/interfaces/cfdiff:cfdiff_" name "_src/interfaces/cfdiff:cfdiff_" ]
  node [ id 1 label "_src/interfaces/cfdiff:Main.cpp_" name "_src/interfaces/cfdiff:Main.cpp_" ]
  node [ id 2 label "_src/interfaces/cfdiff:cfdiff_lib_" name "_src/interfaces/cfdiff:cfdiff_lib_" ]
  node [ id 3 label "_:vcpkg_runtime_libs_" name "_:vcpkg_runtime_libs_" ]
  node [ id 4 label "_at_bazel_toolstools/cpp:malloc_" name "_at_bazel_toolstools/cpp:malloc_" ]
  node [ id 5 label "_at_bazel_toolstools/cpp:link_extra_lib_" name "_at_bazel_toolstools/cpp:link_extra_lib_" ]
  node [ id 6 label "_at_bazel_toolstools/cpp:current_cc_toolchain_" name "_at_bazel_toolstools/cpp:current_cc_toolchain_" ]
  node [ id 7 label "_at_bazel_toolstools/def_parser:def_parser_" name "_at_bazel_toolstools/def_parser:def_parser_" ]
  node [ id 8 label "_at_bazel_toolstools/cpp:toolchain_type_" name "_at_bazel_toolstools/cpp:toolchain_type_" ]
  node [ id 9 label "_src/interfaces/cfdiff:CfDiff.h|src/interfaces/cfdiff:ClassfileDiffApp.h_nsrc/interfaces/cfdiff:ClassfileDiffApp.cpp_" name "_src/interfaces/cfdiff:CfDiff.h|src/interfaces/cfdiff:ClassfileDiffApp.h_nsrc/interfaces/cfdiff:ClassfileDiffApp.cpp_" ]
  node [ id 10 label "_src/app:app_lib_" name "_src/app:app_lib_" ]
  node [ id 11 label "_src:tarracsh_" name "_src:tarracsh_" ]
  node [ id 12 label "_src/interfaces/tarracsh:tarracsh_" name "_src/interfaces/tarracsh:tarracsh_" ]
  node [ id 13 label "_src/interfaces/tarracsh:Main.cpp_" name "_src/interfaces/tarracsh:Main.cpp_" ]
  node [ id 14 label "_src/interfaces/tarracsh:tarracsh_cli_lib_" name "_src/interfaces/tarracsh:tarracsh_cli_lib_" ]
  node [ id 15 label "_at_vcpkg:runtime_libs_" name "_at_vcpkg:runtime_libs_" ]
  node [ id 16 label "_at_vcpkg:installed/x64-linux/lib/libabsl_flags_program_name.a|at_vcpkg:installed/x64-linux/lib/libantlr4-runtime.a_nat_vcpkg:installed/_" name "_at_vcpkg:installed/x64-linux/lib/libabsl_flags_program_name.a|at_vcpkg:installed/x64-linux/lib/libantlr4-runtime.a_nat_vcpkg:installed/_" ]
  node [ id 17 label "_at_vcpkg:headers_" name "_at_vcpkg:headers_" ]
  node [ id 18 label "_src/interfaces/tarracsh:App.h|src/interfaces/tarracsh:App.cpp_" name "_src/interfaces/tarracsh:App.h|src/interfaces/tarracsh:App.cpp_" ]
  node [ id 19 label "_src/app:server/RequestContext.h|src/app:server/digest/ServerCommand.h_nsrc/app:server/digest/ServiceImpl.h_nsrc/app:server/_" name "_src/app:server/RequestContext.h|src/app:server/digest/ServerCommand.h_nsrc/app:server/digest/ServiceImpl.h_nsrc/app:server/_" ]
  node [ id 20 label "_:vcpkg_headers_" name "_:vcpkg_headers_" ]
  node [ id 21 label "_src/domain:domain_lib_" name "_src/domain:domain_lib_" ]
  node [ id 22 label "_src/infrastructure:infrastructure_lib_" name "_src/infrastructure:infrastructure_lib_" ]
  node [ id 23 label "_src/domain:classfile/DescriptorParser.h|src/domain:graph/ClassFileProcessor.h_nsrc/domain:Utils.h_nsrc/domain:classfile/_" name "_src/domain:classfile/DescriptorParser.h|src/domain:graph/ClassFileProcessor.h_nsrc/domain:Utils.h_nsrc/domain:classfile/_" ]
  node [ id 24 label "_src/domain/db:db_lib_" name "_src/domain/db:db_lib_" ]
  node [ id 25 label "_src/domain/db:table/MethodRefEdges.cpp|src/domain/db:table/MethodRefs.cpp_nsrc/domain/db:table/FieldRefEdges.cpp_nsrc/domain/_" name "_src/domain/db:table/MethodRefEdges.cpp|src/domain/db:table/MethodRefs.cpp_nsrc/domain/db:table/FieldRefEdges.cpp_nsrc/domain/_" ]
  node [ id 26 label "_src/infrastructure/string:string_lib_" name "_src/infrastructure/string:string_lib_" ]
  node [ id 27 label "_src/infrastructure/profiling:profiling_lib_" name "_src/infrastructure/profiling:profiling_lib_" ]
  node [ id 28 label "_src/infrastructure/log:log_lib_" name "_src/infrastructure/log:log_lib_" ]
  node [ id 29 label "_src/infrastructure/db:db_lib_" name "_src/infrastructure/db:db_lib_" ]
  node [ id 30 label "_src/infrastructure/app:cli_lib_" name "_src/infrastructure/app:cli_lib_" ]
  node [ id 31 label "_src/infrastructure/filesystem:filesystem_lib_" name "_src/infrastructure/filesystem:filesystem_lib_" ]
  node [ id 32 label "_src/infrastructure/app:CliApp.h|src/infrastructure/app:CliApp.cpp_nsrc/infrastructure/app:Command.h_" name "_src/infrastructure/app:CliApp.h|src/infrastructure/app:CliApp.cpp_nsrc/infrastructure/app:Command.h_" ]
  node [ id 33 label "_src/infrastructure/db:DbConsts.h|src/infrastructure/db:columns/Columns.cpp_nsrc/infrastructure/db:query/Engine.cpp_nsrc/_" name "_src/infrastructure/db:DbConsts.h|src/infrastructure/db:columns/Columns.cpp_nsrc/infrastructure/db:query/Engine.cpp_nsrc/_" ]
  node [ id 34 label "_src/infrastructure/log:Log.h|src/infrastructure/log:Log.cpp_" name "_src/infrastructure/log:Log.h|src/infrastructure/log:Log.cpp_" ]
  node [ id 35 label "_src/infrastructure/profiling:ScopedTimer.cpp|src/infrastructure/profiling:ScopedTimer.h_" name "_src/infrastructure/profiling:ScopedTimer.cpp|src/infrastructure/profiling:ScopedTimer.h_" ]
  node [ id 36 label "_src/infrastructure/filesystem:Utils.cpp|src/infrastructure/filesystem:Utils.h_" name "_src/infrastructure/filesystem:Utils.cpp|src/infrastructure/filesystem:Utils.h_" ]
  node [ id 37 label "_src/infrastructure/string:StringUtils.h_" name "_src/infrastructure/string:StringUtils.h_" ]
  node [ id 38 label "_at_vcpkg:installed/x64-linux/include/google/protobuf/field_access_listener.h|at_vcpkg:installed/x64-linux/include/google/malloc__" name "_at_vcpkg:installed/x64-linux/include/google/protobuf/field_access_listener.h|at_vcpkg:installed/x64-linux/include/google/malloc__" ]
  node [ id 39 label "_atat_platformsos:windows_" name "_atat_platformsos:windows_" ]
  node [ id 40 label "_at_bazel_toolsthird_party/def_parser:def_parser_" name "_at_bazel_toolsthird_party/def_parser:def_parser_" ]
  node [ id 41 label "_at_bazel_toolstools/def_parser:no_op.bat_" name "_at_bazel_toolstools/def_parser:no_op.bat_" ]
  node [ id 42 label "_at_bazel_toolsthird_party/def_parser:def_parser_main.cc_" name "_at_bazel_toolsthird_party/def_parser:def_parser_main.cc_" ]
  node [ id 43 label "_at_bazel_toolsthird_party/def_parser:def_parser_lib_" name "_at_bazel_toolsthird_party/def_parser:def_parser_lib_" ]
  node [ id 44 label "_at_bazel_toolstools/cpp:link_extra_libs_" name "_at_bazel_toolstools/cpp:link_extra_libs_" ]
  node [ id 45 label "_at_bazel_toolstools/cpp:empty_lib_" name "_at_bazel_toolstools/cpp:empty_lib_" ]
  node [ id 46 label "_at_bazel_toolsthird_party/def_parser:def_parser.h|at_bazel_toolsthird_party/def_parser:def_parser.cc_" name "_at_bazel_toolsthird_party/def_parser:def_parser.h|at_bazel_toolsthird_party/def_parser:def_parser.cc_" ]
  node [ id 47 label "_atat_platformsos:os_" name "_atat_platformsos:os_" ]
  node [ id 48 label "_atat_rules_cc_cc:current_cc_toolchain_" name "_atat_rules_cc_cc:current_cc_toolchain_" ]
  edge [ source 0 target 1 ]
  edge [ source 0 target 2 ]
  edge [ source 0 target 3 ]
  edge [ source 0 target 4 ]
  edge [ source 0 target 5 ]
  edge [ source 0 target 6 ]
  edge [ source 0 target 7 ]
  edge [ source 0 target 8 ]
  edge [ source 2 target 6 ]
  edge [ source 2 target 7 ]
  edge [ source 2 target 8 ]
  edge [ source 2 target 9 ]
  edge [ source 2 target 10 ]
  edge [ source 3 target 15 ]
  edge [ source 4 target 6 ]
  edge [ source 4 target 8 ]
  edge [ source 5 target 6 ]
  edge [ source 5 target 8 ]
  edge [ source 5 target 44 ]
  edge [ source 6 target 48 ]
  edge [ source 7 target 39 ]
  edge [ source 7 target 40 ]
  edge [ source 7 target 41 ]
  edge [ source 10 target 6 ]
  edge [ source 10 target 7 ]
  edge [ source 10 target 8 ]
  edge [ source 10 target 19 ]
  edge [ source 10 target 20 ]
  edge [ source 10 target 21 ]
  edge [ source 10 target 22 ]
  edge [ source 11 target 12 ]
  edge [ source 12 target 3 ]
  edge [ source 12 target 4 ]
  edge [ source 12 target 5 ]
  edge [ source 12 target 6 ]
  edge [ source 12 target 7 ]
  edge [ source 12 target 8 ]
  edge [ source 12 target 13 ]
  edge [ source 12 target 14 ]
  edge [ source 14 target 6 ]
  edge [ source 14 target 7 ]
  edge [ source 14 target 8 ]
  edge [ source 14 target 10 ]
  edge [ source 14 target 18 ]
  edge [ source 15 target 6 ]
  edge [ source 15 target 7 ]
  edge [ source 15 target 8 ]
  edge [ source 15 target 16 ]
  edge [ source 15 target 17 ]
  edge [ source 17 target 6 ]
  edge [ source 17 target 7 ]
  edge [ source 17 target 8 ]
  edge [ source 17 target 38 ]
  edge [ source 20 target 17 ]
  edge [ source 21 target 6 ]
  edge [ source 21 target 7 ]
  edge [ source 21 target 8 ]
  edge [ source 21 target 20 ]
  edge [ source 21 target 22 ]
  edge [ source 21 target 23 ]
  edge [ source 21 target 24 ]
  edge [ source 22 target 6 ]
  edge [ source 22 target 7 ]
  edge [ source 22 target 8 ]
  edge [ source 22 target 20 ]
  edge [ source 22 target 26 ]
  edge [ source 22 target 27 ]
  edge [ source 22 target 28 ]
  edge [ source 22 target 29 ]
  edge [ source 22 target 30 ]
  edge [ source 22 target 31 ]
  edge [ source 24 target 6 ]
  edge [ source 24 target 7 ]
  edge [ source 24 target 8 ]
  edge [ source 24 target 20 ]
  edge [ source 24 target 25 ]
  edge [ source 24 target 26 ]
  edge [ source 24 target 27 ]
  edge [ source 24 target 28 ]
  edge [ source 24 target 29 ]
  edge [ source 26 target 6 ]
  edge [ source 26 target 7 ]
  edge [ source 26 target 8 ]
  edge [ source 26 target 20 ]
  edge [ source 26 target 37 ]
  edge [ source 27 target 6 ]
  edge [ source 27 target 7 ]
  edge [ source 27 target 8 ]
  edge [ source 27 target 20 ]
  edge [ source 27 target 31 ]
  edge [ source 27 target 35 ]
  edge [ source 28 target 6 ]
  edge [ source 28 target 7 ]
  edge [ source 28 target 8 ]
  edge [ source 28 target 34 ]
  edge [ source 29 target 6 ]
  edge [ source 29 target 7 ]
  edge [ source 29 target 8 ]
  edge [ source 29 target 20 ]
  edge [ source 29 target 26 ]
  edge [ source 29 target 27 ]
  edge [ source 29 target 28 ]
  edge [ source 29 target 33 ]
  edge [ source 30 target 6 ]
  edge [ source 30 target 7 ]
  edge [ source 30 target 8 ]
  edge [ source 30 target 20 ]
  edge [ source 30 target 28 ]
  edge [ source 30 target 32 ]
  edge [ source 31 target 6 ]
  edge [ source 31 target 7 ]
  edge [ source 31 target 8 ]
  edge [ source 31 target 36 ]
  edge [ source 39 target 47 ]
  edge [ source 40 target 4 ]
  edge [ source 40 target 5 ]
  edge [ source 40 target 6 ]
  edge [ source 40 target 8 ]
  edge [ source 40 target 42 ]
  edge [ source 40 target 43 ]
  edge [ source 43 target 6 ]
  edge [ source 43 target 8 ]
  edge [ source 43 target 46 ]
  edge [ source 44 target 45 ]
  edge [ source 45 target 6 ]
  edge [ source 45 target 8 ]
  edge [ source 48 target 8 ]
]
